JellyDiary/JellyDiary_BE

- build.gradle
- src/main/java/com/ttokttak/jellydiary/user/entity/Authority.java
- src/main/java/com/ttokttak/jellydiary/user/entity/ProviderType.java
- src/main/java/com/ttokttak/jellydiary/user/entity/User.java
- src/main/java/com/ttokttak/jellydiary/user/entity/UserStateEnum.java
- src/main/java/com/ttokttak/jellydiary/user/repository/UserRepository.java
> [JD-160]Feat: User Enum 생성

- src/main/java/com/ttokttak/jellydiary/chat/entity/ChatMessageEntity.java
- src/main/java/com/ttokttak/jellydiary/chat/entity/ChatRoomEntity.java
- src/main/java/com/ttokttak/jellydiary/chat/entity/ChatUserEntity.java
[JD-166] 채팅과 관련된 엔티티 ChatMessageEntity, ChatRoomEntity, ChatUserEntity 구현
[JD-166]: https://ttokttak.atlassian.net/browse/JD-166?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [JD-166]Feat: 채팅 관련 entity 구현

- src/main/java/com/ttokttak/jellydiary/diary/entity/DiaryPostEntity.java
[JD-175]
- erd에서 softDelete 시에 필요한 is_delete를 is_deleted로 명칭을 변경함에 따라 기존 코드도 수정하였습니다.
[JD-175]: https://ttokttak.atlassian.net/browse/JD-175?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [JD-175]Style: DiaryPost entity에서 isDelete -> isDeleted 변경

- src/main/java/com/ttokttak/jellydiary/chat/entity/ChatMessageEntity.java
- src/main/java/com/ttokttak/jellydiary/chat/entity/ChatUserEntity.java
- src/main/java/com/ttokttak/jellydiary/comment/entity/CommentEntity.java
- src/main/java/com/ttokttak/jellydiary/comment/entity/CommentTagEntity.java
- src/main/java/com/ttokttak/jellydiary/like/entity/PostLikeEntity.java
[JD-182]Fix: UserEntity 클래스명 수정에 따른 파생버그 해결
[JD-182]: https://ttokttak.atlassian.net/browse/JD-182?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [JD-182]Fix: UserEntity 클래스명 수정에 따른 파생버그 해결

- src/main/java/com/ttokttak/jellydiary/notification/entity/NotificationSettingEntity.java
[JD-183] NotificationSetting entity 생성
- 식별 관계로 user_id가 pk가 되도록 생성하였습니다.
- ERD에 tag라고 작성된 부분 tag->comment_tag로 이름을 바꾸었고, 이에 따라서 해당 entity에서도 commentTag로 생성해주었습니다.
[JD-183]: https://ttokttak.atlassian.net/browse/JD-183?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [JD-183]Feat: NotificationSetting entity 생성

- build.gradle
- src/main/java/com/ttokttak/jellydiary/JellyDiaryApplication.java
- src/main/java/com/ttokttak/jellydiary/exception/CustomException.java
- src/main/java/com/ttokttak/jellydiary/exception/GlobalExceptionHandler.java
- src/main/java/com/ttokttak/jellydiary/exception/message/ErrorMsg.java
- src/main/java/com/ttokttak/jellydiary/exception/message/SuccessMsg.java
- src/main/java/com/ttokttak/jellydiary/util/dto/ResponseDto.java
[JD-193]
- mapstruct를 사용하려면 lombok을 사용해야하기 때문에 mapstruct dependency가 lombok dependency보다 앞에 있으면 안되기에 해당 부분을 변경해주었습니다.
[JD-194]
- 전역으로 에러를 관리하기 위해서 GlobalException과 CustomException을 생성하였습니다.
[JD-195]
- 통일된 response 형식을 갖추기 위해 ResponseDto를 생성하였습니다.
- Message는 Enum으로 관리하기 위해서 SuccessMsg, ErrorMsg를 생성하였습니다.
[JD-193]: https://ttokttak.atlassian.net/browse/JD-193?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[JD-194]: https://ttokttak.atlassian.net/browse/JD-194?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[JD-195]: https://ttokttak.atlassian.net/browse/JD-195?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [JD-193]mapstruct dependency 위치 변경 [JD-194] GlobalException, CustomException 생성 [JD-195] SuccessMsg, ErrorMsg, ResponseDto 생성

- src/main/java/com/ttokttak/jellydiary/jwt/JWTFilter.java
- src/main/java/com/ttokttak/jellydiary/jwt/JWTUtil.java
- src/main/java/com/ttokttak/jellydiary/user/dto/UserOAuthDto.java
- src/main/java/com/ttokttak/jellydiary/user/dto/oauth2/CustomOAuth2User.java
- src/main/java/com/ttokttak/jellydiary/user/handler/CustomSuccessHandler.java
[JD-196]Fix: JWT TOKEN 생성시 타입오류 수정
[JD-196]: https://ttokttak.atlassian.net/browse/JD-196?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [JD-196]Fix: JWT TOKEN 생성시 타입오류 수정

- src/main/java/com/ttokttak/jellydiary/comment/entity/CommentEntity.java
- src/main/java/com/ttokttak/jellydiary/diary/controller/DiaryController.java
- src/main/java/com/ttokttak/jellydiary/diary/service/DiaryService.java
- src/main/java/com/ttokttak/jellydiary/diarypost/dto/DiaryPostDto.java
- src/main/java/com/ttokttak/jellydiary/diarypost/dto/DiaryPostImgDto.java
- src/main/java/com/ttokttak/jellydiary/diarypost/entity/DiaryPostEntity.java
- src/main/java/com/ttokttak/jellydiary/diarypost/entity/DiaryPostImgEntity.java
- src/main/java/com/ttokttak/jellydiary/diarypost/mapper/DiaryPostImgMapper.java
- src/main/java/com/ttokttak/jellydiary/diarypost/mapper/DiaryPostMapper.java
- src/main/java/com/ttokttak/jellydiary/diarypost/repository/DiaryPostImgRepository.java
- src/main/java/com/ttokttak/jellydiary/diarypost/repository/DiaryPostRepository.java
- src/main/java/com/ttokttak/jellydiary/like/entity/PostLikeEntity.java
[JD-201]
- branch 전략을 기능별로 나누자고 결정했었고, 이에 따라 post와 diary를 별도의 branch로 나누었기에 package도 이를 따라 나누기로 결정하여 관련 Import와 파일들을 수정하였습니다.
[JD-201]: https://ttokttak.atlassian.net/browse/JD-201?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [JD-201]Fix: diarypost package 생성하여 관련 파일과 import 수정

- build.gradle
[JD-202] 다이어리 프로필 생성 pr에서 build.gradle를 누락시켜 다시 추가하였습니다.
[JD-202]: https://ttokttak.atlassian.net/browse/JD-202?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [JD-202]Fix: 다이어리 프로필 생성 pr에서 누락된 build.gradle 추가

- src/main/java/com/ttokttak/jellydiary/diary/controller/DiaryProfileController.java
- src/main/java/com/ttokttak/jellydiary/diary/mapper/DiaryProfileMapper.java
- src/main/java/com/ttokttak/jellydiary/diary/repository/DiaryUserRepository.java
- src/main/java/com/ttokttak/jellydiary/diary/service/DiaryProfileService.java
- src/main/java/com/ttokttak/jellydiary/diary/service/DiaryProfileServiceImpl.java
- src/main/java/com/ttokttak/jellydiary/exception/message/SuccessMsg.java
[JD-118]Feat: 내가 구독 또는 참여 중인 다이어리 리스트 조회 api 구현
- 로그인 한 사용자가 구독 중이거나 또는 참여 중인 다이어리 리스트를 조회하는 api를 구현했습니다.
[JD-118]: https://ttokttak.atlassian.net/browse/JD-118?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [JD-118]Feat: 내가 구독 또는 참여 중인 다이어리 리스트 조회 api 구현

- src/main/java/com/ttokttak/jellydiary/diary/service/DiaryUserService.java
- src/main/java/com/ttokttak/jellydiary/diarypost/controller/DiaryPostController.java
- src/main/java/com/ttokttak/jellydiary/diarypost/dto/DiaryPostCreateRequestDto.java
- src/main/java/com/ttokttak/jellydiary/diarypost/dto/DiaryPostCreateResponseDto.java
- src/main/java/com/ttokttak/jellydiary/diarypost/dto/DiaryPostImgListRequestDto.java
- src/main/java/com/ttokttak/jellydiary/diarypost/dto/DiaryPostImgListResponseDto.java
- src/main/java/com/ttokttak/jellydiary/diarypost/entity/DiaryPostEntity.java
- src/main/java/com/ttokttak/jellydiary/diarypost/entity/DiaryPostImgEntity.java
- src/main/java/com/ttokttak/jellydiary/diarypost/entity/WeatherEnum.java
- src/main/java/com/ttokttak/jellydiary/diarypost/mapper/DiaryPostImgMapper.java
- src/main/java/com/ttokttak/jellydiary/diarypost/mapper/DiaryPostMapper.java
- src/main/java/com/ttokttak/jellydiary/diarypost/repository/DiaryPostImgRepository.java
- src/main/java/com/ttokttak/jellydiary/diarypost/service/DiaryPostService.java
- src/main/java/com/ttokttak/jellydiary/diarypost/service/DiaryPostServiceImpl.java
- src/main/java/com/ttokttak/jellydiary/exception/message/ErrorMsg.java
- src/main/java/com/ttokttak/jellydiary/exception/message/SuccessMsg.java
[JD-210]
- 일자는 오늘보타 미래 날짜로 선택되어 요청이 온다면 예외처리를 해주었습니다.
- 이미지는 List<MultipartFile>로 여러장 받을 수 있도록 하였습니다.
- 요청한 사용자의 다이어리 내 권한이 CREATOR, READ가 아니고 getIsInvited이 true가 아니면 예외처리를 해주었습니다.
- 작업 중 develop에 Merge된 작업물을 받던중에 conflict가 발생하여 이를 해결하고자 관련 파일들을 수정하였습니다.
[JD-210]: https://ttokttak.atlassian.net/browse/JD-210?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [JD-210]Feat: 게시물 생성 api 구현

- src/main/java/com/ttokttak/jellydiary/diarypost/controller/DiaryPostController.java
- src/main/java/com/ttokttak/jellydiary/diarypost/mapper/DiaryPostImgMapper.java
- src/main/java/com/ttokttak/jellydiary/diarypost/service/DiaryPostServiceImpl.java
[JD-212]
- postImg에 null과 빈배열을 보냈을 때도 DB에 행이 추가되는 것을 알게되어  required = false 추가 후 null과 isEmpty() if문 처리
[JD-212]: https://ttokttak.atlassian.net/browse/JD-212?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [JD-212]Fix: postImg null 처리

- src/main/java/com/ttokttak/jellydiary/diary/service/DiaryUserServiceImpl.java
다음의 경우에 다이어리 유저가 삭제되도록 구현했습니다.
- 초대 거절 (다이어리 생성자가 아닐 때)
- 구독 취소 또는 다이어리 참여 취소 (다이어리 생성자가 아닐 때)
- 다이어리 생성자가 다이어리 참여자를 삭제할 때
- 다이어리 생성자가 초대를 취소할 때.
> [JD-214]Fix: 다이어리 유저 삭제 api 수정

- .github/workflows/deploy.yml
- .github/workflows/gradle.yml
- Dockerfile
- docker-compose.yml
[JD-216]Util: CI/CD 관련 설정
Dockerfile 작성
docker-compose.yml 작성
CI => gradle.yml 작성
CD => deploy.yml 작성
[JD-216]: https://ttokttak.atlassian.net/browse/JD-216?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [JD-216]Util: CI/CD 관련 설정

- .github/workflows/gradle.yml
- src/main/java/com/ttokttak/jellydiary/diarypost/controller/DiaryPostController.java
- src/main/java/com/ttokttak/jellydiary/diarypost/entity/DiaryPostEntity.java
- src/main/java/com/ttokttak/jellydiary/diarypost/service/DiaryPostService.java
- src/main/java/com/ttokttak/jellydiary/diarypost/service/DiaryPostServiceImpl.java
- src/main/java/com/ttokttak/jellydiary/exception/message/ErrorMsg.java
- src/main/java/com/ttokttak/jellydiary/exception/message/SuccessMsg.java
[JD-221]
- softDelete로 게시물 삭제 및 게시물 이미지 삭제 기능을 구현 완료하였습니다.
[JD-221]: https://ttokttak.atlassian.net/browse/JD-221?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
>  [JD-221]Feat: 게시물 삭제 api 구현

- build.gradle
[JD-220]Chore: build.gradle 수정
- CI오류 해결을 위해 tasks.named('test')를 test로 명시
- 데이터베이스 H2 => mysql로 변경
[JD-220]: https://ttokttak.atlassian.net/browse/JD-220?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [JD-220]Chore: build.gradle 수정

- .github/workflows/deploy.yml
- .gitignore
[JD-222][JD-223] gitignore 수정, CD workflow 수정
[JD-222]: https://ttokttak.atlassian.net/browse/JD-222?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [JD-222][JD-223] gitignore 수정, CD workflow 수정

- .gitignore
- src/main/java/com/ttokttak/jellydiary/diarypost/controller/DiaryPostController.java
- src/main/java/com/ttokttak/jellydiary/diarypost/dto/DiaryPostListResponseDto.java
- src/main/java/com/ttokttak/jellydiary/diarypost/mapper/DiaryPostMapper.java
- src/main/java/com/ttokttak/jellydiary/diarypost/repository/DiaryPostRepository.java
- src/main/java/com/ttokttak/jellydiary/diarypost/service/DiaryPostService.java
- src/main/java/com/ttokttak/jellydiary/diarypost/service/DiaryPostServiceImpl.java
- src/main/java/com/ttokttak/jellydiary/exception/message/SuccessMsg.java
[JD-122]
- 다이어리 유저 권한이 SUBSCRIBE 인 경우 isPublic이 false인건 조회하지 못하도록 구현하였습니다.
[JD-122]: https://ttokttak.atlassian.net/browse/JD-122?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [JD-122]Feat: 게시글 리스트 조회 api 구현

- src/main/java/com/ttokttak/jellydiary/diarypost/entity/DiaryPostEntity.java
- src/main/java/com/ttokttak/jellydiary/diarypost/entity/DiaryPostImgEntity.java
- src/main/java/com/ttokttak/jellydiary/diarypost/repository/DiaryPostImgRepository.java
- src/main/java/com/ttokttak/jellydiary/diarypost/repository/DiaryPostRepository.java
- src/main/java/com/ttokttak/jellydiary/diarypost/service/DiaryPostServiceImpl.java
- src/main/java/com/ttokttak/jellydiary/exception/message/ErrorMsg.java
[JD-227]
- @Where이 deprcated 경고 문구가 뜨는 것을 확인하여 모든 @Where을 삭제하고 @Query와 if(getIsDeleted())로 처리하였습니다.
[JD-227]: https://ttokttak.atlassian.net/browse/JD-227?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [JD-227]Fix: @Where절 삭제 후 @Query와 if(getIsDeleted())로 select 처리

- src/main/java/com/ttokttak/jellydiary/exception/message/ErrorMsg.java
- src/main/java/com/ttokttak/jellydiary/exception/message/SuccessMsg.java
- src/main/java/com/ttokttak/jellydiary/feed/controller/FeedController.java
- src/main/java/com/ttokttak/jellydiary/feed/service/FeedService.java
- src/main/java/com/ttokttak/jellydiary/feed/service/FeedServiceImpl.java
- src/main/java/com/ttokttak/jellydiary/follow/entity/FollowEntity.java
[JD-134]Feat: 팔로우 신청 api 구현
- 자기 자신을 팔로우 할 수 없도록 구현했습니다.
[JD-134]: https://ttokttak.atlassian.net/browse/JD-134?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [JD-134]Feat: 팔로우 신청 api 구현

- src/main/java/com/ttokttak/jellydiary/exception/message/SuccessMsg.java
- src/main/java/com/ttokttak/jellydiary/feed/controller/FeedController.java
- src/main/java/com/ttokttak/jellydiary/feed/service/FeedService.java
- src/main/java/com/ttokttak/jellydiary/feed/service/FeedServiceImpl.java
[JD-135]Feat: 팔로우 취소 api 입니다.
[JD-135]: https://ttokttak.atlassian.net/browse/JD-135?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [JD-135]Feat: 팔로우 취소 api 구현

- src/main/java/com/ttokttak/jellydiary/exception/message/SuccessMsg.java
- src/main/java/com/ttokttak/jellydiary/like/controller/PostLikeController.java
- src/main/java/com/ttokttak/jellydiary/like/dto/PostLikeMapper.java
- src/main/java/com/ttokttak/jellydiary/like/entity/PostLikeEntity.java
- src/main/java/com/ttokttak/jellydiary/like/repository/PostLikeRepository.java
- src/main/java/com/ttokttak/jellydiary/like/service/PostLikeService.java
- src/main/java/com/ttokttak/jellydiary/like/service/PostLikeServiceImpl.java
[JD-229]
- 복합키를 활용한 좋아요 등록 api 구현을 완료하였습니다.
[JD-229]: https://ttokttak.atlassian.net/browse/JD-229?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [JD-229]Feat: 좋아요 등록 api 구현

- src/main/java/com/ttokttak/jellydiary/exception/message/SuccessMsg.java
- src/main/java/com/ttokttak/jellydiary/like/controller/PostLikeController.java
- src/main/java/com/ttokttak/jellydiary/like/dto/PostLikeGetResponseDto.java
- src/main/java/com/ttokttak/jellydiary/like/repository/PostLikeRepository.java
- src/main/java/com/ttokttak/jellydiary/like/service/PostLikeService.java
- src/main/java/com/ttokttak/jellydiary/like/service/PostLikeServiceImpl.java
[JD-230]
- 게시글 좋아요 상태를 조회하여 값이 null이면 false, null이 아니면 true를 response해주도록 구현하였습니다.
[JD-230]: https://ttokttak.atlassian.net/browse/JD-230?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [JD-230]Feat: 게시글 좋아요 상태 조회 api 구현

- src/main/java/com/ttokttak/jellydiary/comment/controller/CommentController.java
- src/main/java/com/ttokttak/jellydiary/comment/dto/CommentCreateCommentInfoDto.java
- src/main/java/com/ttokttak/jellydiary/comment/dto/CommentCreateRequestDto.java
- src/main/java/com/ttokttak/jellydiary/comment/dto/CommentCreateResponseDto.java
- src/main/java/com/ttokttak/jellydiary/comment/dto/CommentMapper.java
- src/main/java/com/ttokttak/jellydiary/comment/dto/CommentTagMapper.java
- src/main/java/com/ttokttak/jellydiary/comment/dto/CommentUserTagInfoDto.java
- src/main/java/com/ttokttak/jellydiary/comment/entity/CommentEntity.java
- src/main/java/com/ttokttak/jellydiary/comment/entity/CommentTagCompositeKey.java
- src/main/java/com/ttokttak/jellydiary/comment/entity/CommentTagEntity.java
- src/main/java/com/ttokttak/jellydiary/comment/repository/CommentRepository.java
- src/main/java/com/ttokttak/jellydiary/comment/repository/CommentTagRepository.java
- src/main/java/com/ttokttak/jellydiary/comment/service/CommentService.java
- src/main/java/com/ttokttak/jellydiary/comment/service/CommentServiceImpl.java
- src/main/java/com/ttokttak/jellydiary/exception/message/ErrorMsg.java
- src/main/java/com/ttokttak/jellydiary/exception/message/SuccessMsg.java
- src/main/java/com/ttokttak/jellydiary/like/controller/PostLikeController.java
- src/main/java/com/ttokttak/jellydiary/user/entity/UserEntity.java
[JD-234]
- 일반 사용자와 구독자는 비공개 게시글에 접근하지 못하도록 댓글 작성을 구현하였습니다.
[JD-234]: https://ttokttak.atlassian.net/browse/JD-234?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [JD-234]Feat: 게시글에 댓글 작성 api 구현

- src/main/java/com/ttokttak/jellydiary/diarypost/controller/DiaryPostController.java
- src/main/java/com/ttokttak/jellydiary/diarypost/dto/DiaryPostGetOneResponseDto.java
- src/main/java/com/ttokttak/jellydiary/diarypost/dto/DiaryPostImgListRequestDto.java
- src/main/java/com/ttokttak/jellydiary/diarypost/mapper/DiaryPostMapper.java
- src/main/java/com/ttokttak/jellydiary/diarypost/service/DiaryPostService.java
- src/main/java/com/ttokttak/jellydiary/diarypost/service/DiaryPostServiceImpl.java
- src/main/java/com/ttokttak/jellydiary/exception/message/SuccessMsg.java
- src/main/java/com/ttokttak/jellydiary/like/repository/PostLikeRepository.java
[JD-235] 
- 구독자, 일반 사용자는 비공개 게시글에 접근하지 못하도록 처리하였고 좋아요 수를 response 해줄 수 있도록게시글 상세 조회를 구현하였습니다.
[JD-235]: https://ttokttak.atlassian.net/browse/JD-235?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [JD-235]Feat: 게시글 상세 조회 구현

- src/main/java/com/ttokttak/jellydiary/comment/controller/CommentController.java
- src/main/java/com/ttokttak/jellydiary/comment/dto/CommentMapper.java
- src/main/java/com/ttokttak/jellydiary/comment/dto/ReplyCommentCreateCommentInfoDto.java
- src/main/java/com/ttokttak/jellydiary/comment/dto/ReplyCommentCreateResponseDto.java
- src/main/java/com/ttokttak/jellydiary/comment/service/CommentService.java
- src/main/java/com/ttokttak/jellydiary/comment/service/CommentServiceImpl.java
- src/main/java/com/ttokttak/jellydiary/exception/message/ErrorMsg.java
- src/main/java/com/ttokttak/jellydiary/exception/message/SuccessMsg.java
[JD-236]
- depth를 1개로 정했기 때문에 parentId가 null인.. 즉, 댓글에만 답글을 작성할 수 있고, 
parentId가 null이 아닌.. 즉, 또 다른 답글에는 답글을 달지 못하도록 답글 작성 api를 구현하였습니다.
[JD-236]: https://ttokttak.atlassian.net/browse/JD-236?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [JD-236]Feat: 댓글에 답글 달기 api 구현

- src/main/java/com/ttokttak/jellydiary/exception/message/ErrorMsg.java
- src/main/java/com/ttokttak/jellydiary/exception/message/SuccessMsg.java
- src/main/java/com/ttokttak/jellydiary/notification/entity/NotificationSettingEntity.java
- src/main/java/com/ttokttak/jellydiary/notification/repository/NotificationSettingRepository.java
- src/main/java/com/ttokttak/jellydiary/user/controller/UserController.java
- src/main/java/com/ttokttak/jellydiary/user/dto/UserProfileDto.java
- src/main/java/com/ttokttak/jellydiary/user/entity/UserEntity.java
- src/main/java/com/ttokttak/jellydiary/user/mapper/UserMapper.java
- src/main/java/com/ttokttak/jellydiary/user/service/UserService.java
- src/main/java/com/ttokttak/jellydiary/user/service/UserServiceImpl.java
[JD-77]Feat: 유저 프로필 조회 api 구현
[JD-77]: https://ttokttak.atlassian.net/browse/JD-77?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [JD-77]Feat: 유저 프로필 조회 api 구현

- src/main/java/com/ttokttak/jellydiary/comment/controller/CommentController.java
- src/main/java/com/ttokttak/jellydiary/comment/dto/CommentDeleteResponseDto.java
- src/main/java/com/ttokttak/jellydiary/comment/dto/CommentMapper.java
- src/main/java/com/ttokttak/jellydiary/comment/entity/CommentEntity.java
- src/main/java/com/ttokttak/jellydiary/comment/service/CommentService.java
- src/main/java/com/ttokttak/jellydiary/comment/service/CommentServiceImpl.java
- src/main/java/com/ttokttak/jellydiary/diarypost/repository/DiaryPostRepository.java
- src/main/java/com/ttokttak/jellydiary/exception/message/ErrorMsg.java
- src/main/java/com/ttokttak/jellydiary/exception/message/SuccessMsg.java
[JD-243]
- 댓글/답글 삭제 api를 구현하였습니다.
- response에서 isDeleted값을 출력하는 과정에서 오류를 만나 해당 부분은 TODO로 작성해두었고, 추후 수정할 예정입니다.
[JD-243]: https://ttokttak.atlassian.net/browse/JD-243?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [JD-243]Feat: 댓글 삭제 api 구현

- src/main/java/com/ttokttak/jellydiary/comment/repository/CommentRepository.java
- src/main/java/com/ttokttak/jellydiary/diarypost/dto/DiaryPostGetOneResponseDto.java
- src/main/java/com/ttokttak/jellydiary/diarypost/mapper/DiaryPostMapper.java
- src/main/java/com/ttokttak/jellydiary/diarypost/service/DiaryPostServiceImpl.java
[JD-244]
- 게시글 상세 조회 시에 게시물에 달린 댓글수를 확인할 수 있도록 이를 response에 추가하였습니다.
[JD-244]: https://ttokttak.atlassian.net/browse/JD-244?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [JD-244]Feat: 게시물 상세 조회 response에 게시물에 달린 댓글수 추가

- src/main/java/com/ttokttak/jellydiary/exception/message/SuccessMsg.java
- src/main/java/com/ttokttak/jellydiary/user/controller/UserController.java
- src/main/java/com/ttokttak/jellydiary/user/dto/UserProfileUpdateRequestDto.java
- src/main/java/com/ttokttak/jellydiary/user/dto/UserProfileUpdateResponseDto.java
- src/main/java/com/ttokttak/jellydiary/user/entity/UserEntity.java
- src/main/java/com/ttokttak/jellydiary/user/mapper/UserMapper.java
- src/main/java/com/ttokttak/jellydiary/user/service/UserService.java
- src/main/java/com/ttokttak/jellydiary/user/service/UserServiceImpl.java
[JD-78]Feat: 유저 프로필 수정 api 구현
[JD-78]: https://ttokttak.atlassian.net/browse/JD-78?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [JD-78]Feat: 유저 프로필 수정 api 구현

- src/main/java/com/ttokttak/jellydiary/exception/message/SuccessMsg.java
- src/main/java/com/ttokttak/jellydiary/notification/entity/NotificationSettingEntity.java
- src/main/java/com/ttokttak/jellydiary/user/controller/UserController.java
- src/main/java/com/ttokttak/jellydiary/user/dto/UserNotificationSettingRequestDto.java
- src/main/java/com/ttokttak/jellydiary/user/dto/UserNotificationSettingResponseDto.java
- src/main/java/com/ttokttak/jellydiary/user/entity/UserEntity.java
- src/main/java/com/ttokttak/jellydiary/user/mapper/UserMapper.java
- src/main/java/com/ttokttak/jellydiary/user/service/UserService.java
- src/main/java/com/ttokttak/jellydiary/user/service/UserServiceImpl.java
[JD-80]Feat: 유저 알림 설정 api 구현
[JD-80]: https://ttokttak.atlassian.net/browse/JD-80?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [JD-80]Feat: 유저 알림 설정 api 구현

- src/main/java/com/ttokttak/jellydiary/diarypost/mapper/DiaryPostImgMapper.java
- src/main/java/com/ttokttak/jellydiary/diarypost/service/DiaryPostServiceImpl.java
- src/main/java/com/ttokttak/jellydiary/exception/message/ErrorMsg.java
- src/main/java/com/ttokttak/jellydiary/util/S3Uploader.java
[JD-254] 게시물 작성
[JD-255] 게시물 수정
- 게시물 작성, 수정 시 s3업로드 추가 및 5개이상은 업로드 하지 못하도록 예외처리를 하여 구현하였습니다.
[JD-254]: https://ttokttak.atlassian.net/browse/JD-254?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[JD-255]: https://ttokttak.atlassian.net/browse/JD-255?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [JD-254][JD-255]Feat: 게시물 작성 수정 시 s3업로드 구현 및 5개이상은 업로드 하지 못하도록 제한

- src/main/java/com/ttokttak/jellydiary/chat/entity/ChatMessageEntity.java
- src/main/java/com/ttokttak/jellydiary/chat/entity/ChatRoomEntity.java
- src/main/java/com/ttokttak/jellydiary/chat/entity/ChatUserEntity.java
[JD-258]Fix: chat 관련 엔티티 @ Table 누락 수정
- @ Entity(name = "~~~")으로 작성된 부분을 @ Table(name = "~~~") 으로 수정했습니다.
[JD-258]: https://ttokttak.atlassian.net/browse/JD-258?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [JD-258]Fix: chat 관련 엔티티 @ Table 누락 수정

- src/main/java/com/ttokttak/jellydiary/diarypost/service/DiaryPostServiceImpl.java
- src/main/java/com/ttokttak/jellydiary/sns/controller/SnsController.java
- src/main/java/com/ttokttak/jellydiary/sns/service/SnsService.java
- src/main/java/com/ttokttak/jellydiary/sns/service/SnsServiceImpl.java
[JD-260]
- DiaryPost 수정에서 필요없는 코드가 확인되어 제거하였습니다.
[JD-260]: https://ttokttak.atlassian.net/browse/JD-260?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [JD-260]Fix: DiaryPost 수정 필요없는 코드 제거

- src/main/java/com/ttokttak/jellydiary/chat/repository/ChatUserRepository.java
- src/main/java/com/ttokttak/jellydiary/diary/service/DiaryUserServiceImpl.java
- src/main/java/com/ttokttak/jellydiary/exception/message/ErrorMsg.java
[JD-264]Fix: 다이어리 초대 승인 시 다이어리 그룹 채팅방에 자동으로 참여되도록 수정
- 다이어리 초대를 승인하면 다이어리 그룹 채팅방에 자동으로 참여되도록 수정했습니다.
[JD-264]: https://ttokttak.atlassian.net/browse/JD-264?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [JD-264]Fix: 다이어리 초대 승인 시 다이어리 그룹 채팅방에 자동으로 참여되도록 수정

- src/main/java/com/ttokttak/jellydiary/diarypost/mapper/DiaryPostImgMapper.java
- src/main/java/com/ttokttak/jellydiary/diarypost/service/DiaryPostServiceImpl.java
- src/main/java/com/ttokttak/jellydiary/exception/message/ErrorMsg.java
[JD-267]
- 이미지 수정 시 newPostImgs가 null일 때도 List의 size()를 확인하고 있어서 오류가 발생하는 것을 발견하여 해당 부분을 if()문을 추가하여 해결하였습니다.
[JD-267]: https://ttokttak.atlassian.net/browse/JD-267?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [JD-267]Fix: 이미지 수정 시 newPostImgs가 null일 시 if() 문 추가

- src/main/java/com/ttokttak/jellydiary/chat/controller/ChatMessageController.java
- src/main/java/com/ttokttak/jellydiary/chat/dto/ChatMessageRequestDto.java
- src/main/java/com/ttokttak/jellydiary/chat/dto/ChatMessageResponseDto.java
- src/main/java/com/ttokttak/jellydiary/chat/entity/ChatMessageEntity.java
- src/main/java/com/ttokttak/jellydiary/chat/mapper/ChatMessageMapper.java
- src/main/java/com/ttokttak/jellydiary/chat/repository/ChatMessageRepository.java
- src/main/java/com/ttokttak/jellydiary/chat/service/ChatMessageService.java
- src/main/java/com/ttokttak/jellydiary/chat/service/ChatMessageServiceImpl.java
- src/main/java/com/ttokttak/jellydiary/chat/service/ChatRoomService.java
- src/main/java/com/ttokttak/jellydiary/chat/service/ChatRoomServiceImpl.java
- src/main/java/com/ttokttak/jellydiary/config/SecurityConfig.java
- src/main/java/com/ttokttak/jellydiary/config/WebSocketConfig.java
[JD-271]Feat: 채팅 메시지 보내기 - 임시 ver
- 채팅 보내기의 임시 버전입니다. 현재는 메시지를 보내는 사람(즉, 로그인한 사용자)의 정보를 프론트엔드에서 전달받아 처리하고 있습니다. 하지만 이후에는 JWT 검증을 통해 사용자 정보를 자동으로 가져와 입력하는 것으로 수정할 예정입니다.
[JD-271]: https://ttokttak.atlassian.net/browse/JD-271?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [JD-271]Feat: 채팅 메시지 보내기 - 임시 ver

- build.gradle
- src/main/java/com/ttokttak/jellydiary/config/QuerydslConfig.java
- src/main/java/com/ttokttak/jellydiary/diarypost/entity/DiaryPostEntity.java
- src/main/java/com/ttokttak/jellydiary/diarypost/repository/DiaryPostImgRepository.java
- src/main/java/com/ttokttak/jellydiary/diarypost/repository/DiaryPostRepository.java
- src/main/java/com/ttokttak/jellydiary/diarypost/repository/DiaryPostRepositoryCustom.java
- src/main/java/com/ttokttak/jellydiary/diarypost/repository/DiaryPostRepositoryCustomImpl.java
- src/main/java/com/ttokttak/jellydiary/exception/message/SuccessMsg.java
- src/main/java/com/ttokttak/jellydiary/sns/SnsMapper.java
- src/main/java/com/ttokttak/jellydiary/sns/controller/SnsController.java
- src/main/java/com/ttokttak/jellydiary/sns/dto/SnsGetListResponseDto.java
- src/main/java/com/ttokttak/jellydiary/sns/service/SnsServiceImpl.java
[JD-273]
- QueryDsl 설정 및 sns 관련 구조 세팅을 진행했습니다.
[JD-273]: https://ttokttak.atlassian.net/browse/JD-273?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [JD-273]Feat: QueryDsl 설정 및 sns 관련 구조 세팅

- src/main/java/com/ttokttak/jellydiary/chat/dto/ChatRoomResponseDto.java
- src/main/java/com/ttokttak/jellydiary/chat/service/ChatRoomServiceImpl.java
[JD-274]Fix: ChatRoomResponseDto에 createdAt 필드 추가
- ChatRoomResponseDto에 최신 메시지의 생성 날짜를 나타내는 createdAt 필드를 추가했습니다.
[JD-274]: https://ttokttak.atlassian.net/browse/JD-274?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [JD-274]Fix: ChatRoomResponseDto에 createdAt 필드 추가

- src/main/java/com/ttokttak/jellydiary/chat/dto/ChatRoomResponseDto.java
- src/main/java/com/ttokttak/jellydiary/chat/service/ChatRoomServiceImpl.java
[JD-277]Fix: ChatRoomResponseDto에 userId, diaryId 필드 추가했습니다.
[JD-277]: https://ttokttak.atlassian.net/browse/JD-277?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [JD-277]Fix: ChatRoomResponseDto에 userId, diaryId 필드 추가

- src/main/java/com/ttokttak/jellydiary/chat/dto/ChatMessageResponseDto.java
- src/main/java/com/ttokttak/jellydiary/chat/mapper/ChatMessageMapper.java
[JD-279]Fix: ChatMessageResponseDto에 userProfileImg 필드 추가
[JD-279]: https://ttokttak.atlassian.net/browse/JD-279?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [JD-279]Fix: ChatMessageResponseDto에 userProfileImg 필드 추가

- src/main/java/com/ttokttak/jellydiary/chat/repository/ChatMessageRepository.java
- src/main/java/com/ttokttak/jellydiary/chat/service/ChatRoomServiceImpl.java
[JD-280]Fix: ChatMessageRepository 수정 - 1개의 엔티티만 조회하는 쿼리 수정
- 가장 최근 메시지 1개를 조회하는 쿼리를 수정했습니다.
[JD-280]: https://ttokttak.atlassian.net/browse/JD-280?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [JD-280]Fix: ChatMessageRepository 수정 - 1개의 엔티티만 조회하는 쿼리 수정

- src/main/java/com/ttokttak/jellydiary/diary/controller/DiaryProfileController.java
- src/main/java/com/ttokttak/jellydiary/diary/service/DiaryProfileService.java
- src/main/java/com/ttokttak/jellydiary/diary/service/DiaryProfileServiceImpl.java
[JD-282]Fix: 다이어리 프로필 사진 업로드 코드 추가
- 다이어리 프로필 생성 시 프로필 사진을 업로드할 수 있도록 코드를 추가했습니다.
[JD-282]: https://ttokttak.atlassian.net/browse/JD-282?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [JD-282]Fix: 다이어리 프로필 사진 업로드 코드 추가

- src/main/java/com/ttokttak/jellydiary/user/controller/ReissueController.java
[JD-285]Fix: ReissueController의 Return형식 변경
[JD-285]: https://ttokttak.atlassian.net/browse/JD-285?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [JD-285]Fix: ReissueController의 Return형식 변경

- src/main/java/com/ttokttak/jellydiary/chat/dto/ChatMessageListResponseDto.java
- src/main/java/com/ttokttak/jellydiary/chat/service/ChatMessageServiceImpl.java
[JD-286]Fix: ChatMessageListResponseDto에 page 필드 추가
[JD-286]: https://ttokttak.atlassian.net/browse/JD-286?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [JD-286]Fix: ChatMessageListResponseDto에 page 필드 추가

- src/main/java/com/ttokttak/jellydiary/notification/controller/NotificationController.java
- src/main/java/com/ttokttak/jellydiary/notification/dto/NotificationResponseDto.java
- src/main/java/com/ttokttak/jellydiary/notification/entity/NotificationContent.java
- src/main/java/com/ttokttak/jellydiary/notification/entity/NotificationEntity.java
- src/main/java/com/ttokttak/jellydiary/notification/entity/NotificationType.java
- src/main/java/com/ttokttak/jellydiary/notification/mapper/NotificationMapper.java
- src/main/java/com/ttokttak/jellydiary/notification/repository/NotificationRepository.java
- src/main/java/com/ttokttak/jellydiary/notification/repository/SseRepository.java
- src/main/java/com/ttokttak/jellydiary/notification/repository/SseRepositoryImpl.java
- src/main/java/com/ttokttak/jellydiary/notification/service/NotificationService.java
- src/main/java/com/ttokttak/jellydiary/notification/service/NotificationServiceImpl.java
[JD-291]
- SSE 연결 api와 Notification entity를 생성한 후 다른 api들의 service 로직에 넣을 send 메서드를 추가하였습니다.
[JD-291]: https://ttokttak.atlassian.net/browse/JD-291?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [JD-291]Feat: SSE 연결 api와 Notification entity 생성 및 관련 로직 추가

- src/main/java/com/ttokttak/jellydiary/config/SecurityConfig.java
- src/main/java/com/ttokttak/jellydiary/exception/message/SuccessMsg.java
- src/main/java/com/ttokttak/jellydiary/jwt/CustomLogoutFilter.java
[JD-292]Feat: 유저 로그아웃 api 구현
- /api/logout 요청이 POST로 들어왔을때 로그아웃 로직 수행
[JD-292]: https://ttokttak.atlassian.net/browse/JD-292?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [JD-292]Feat: 유저 로그아웃 api 구현

- src/main/java/com/ttokttak/jellydiary/diary/repository/DiaryUserRepository.java
- src/main/java/com/ttokttak/jellydiary/diarypost/service/DiaryPostServiceImpl.java
- src/main/java/com/ttokttak/jellydiary/notification/controller/NotificationController.java
- src/main/java/com/ttokttak/jellydiary/notification/dto/NotificationResponseDto.java
- src/main/java/com/ttokttak/jellydiary/notification/entity/NotificationContent.java
- src/main/java/com/ttokttak/jellydiary/notification/entity/NotificationEntity.java
- src/main/java/com/ttokttak/jellydiary/notification/entity/NotificationSettingEntity.java
- src/main/java/com/ttokttak/jellydiary/notification/entity/NotificationType.java
- src/main/java/com/ttokttak/jellydiary/notification/mapper/NotificationMapper.java
- src/main/java/com/ttokttak/jellydiary/notification/repository/NotificationRepository.java
- src/main/java/com/ttokttak/jellydiary/notification/repository/SseRepository.java
- src/main/java/com/ttokttak/jellydiary/notification/repository/SseRepositoryImpl.java
- src/main/java/com/ttokttak/jellydiary/notification/service/NotificationService.java
- src/main/java/com/ttokttak/jellydiary/notification/service/NotificationServiceImpl.java
- src/main/java/com/ttokttak/jellydiary/user/dto/UserNotificationSettingRequestDto.java
- src/main/java/com/ttokttak/jellydiary/user/entity/UserEntity.java
- src/main/java/com/ttokttak/jellydiary/user/service/UserServiceImpl.java
[JD-293]
- notification setting entity에 post와 diary 컬럼을 추가하였습니다.
- 게시물 생성 시 알림 로직을 추가하였습니다.
[JD-293]: https://ttokttak.atlassian.net/browse/JD-293?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [JD-293]Feat: notification setting entity 변경 및 게시물 생성 시 알림 로직 추가

- src/main/java/com/ttokttak/jellydiary/user/dto/oauth2/GoogleResponse.java
- src/main/java/com/ttokttak/jellydiary/user/dto/oauth2/NaverResponse.java
- src/main/java/com/ttokttak/jellydiary/user/dto/oauth2/OAuth2Response.java
- src/main/java/com/ttokttak/jellydiary/user/entity/UserEntity.java
- src/main/java/com/ttokttak/jellydiary/user/service/CustomOAuth2UserService.java
[JD-294]Feat: 소셜로그인 진행시 email은 가져오지 않는 것으로 수정
[JD-294]: https://ttokttak.atlassian.net/browse/JD-294?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [JD-294]Feat: 소셜로그인 진행시 email은 가져오지 않는 것으로 수정

- src/main/java/com/ttokttak/jellydiary/user/dto/oauth2/KakaoResponse.java
- src/main/java/com/ttokttak/jellydiary/user/service/CustomOAuth2UserService.java
[JD-188]Feat: Kakao 소셜 로그인 구현
[JD-188]: https://ttokttak.atlassian.net/browse/JD-188?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [JD-188]Feat: Kakao 소셜 로그인 구현

- src/main/java/com/ttokttak/jellydiary/user/service/CustomOAuth2UserService.java
[JD-296]Fix: 회원가입시 유저 이름을 저장할때 닉네임 규정에 맞게 수정 후 저장
[JD-296]: https://ttokttak.atlassian.net/browse/JD-296?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [JD-296]Fix: 회원가입시 유저 이름을 저장할때 닉네임 규정에 맞게 수정 후 저장

- src/main/java/com/ttokttak/jellydiary/comment/service/CommentServiceImpl.java
- src/main/java/com/ttokttak/jellydiary/diarypost/service/DiaryPostServiceImpl.java
- src/main/java/com/ttokttak/jellydiary/like/service/PostLikeServiceImpl.java
- src/main/java/com/ttokttak/jellydiary/notification/controller/NotificationController.java
- src/main/java/com/ttokttak/jellydiary/notification/entity/NotificationType.java
[JD-297]
- 게시물 생성, 댓글 생성, 답글 생성, 댓글 언급, 게시물 좋아요 시 알림 로직을 추가하였습니다.
- NotificationType에 답글 생성과 관련된 알림 메시지를 추가하였습니다.
[JD-297]: https://ttokttak.atlassian.net/browse/JD-297?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [JD-297]Feat: 게시물 생성, 댓글 생성, 답글 생성, 댓글 언급, 게시물 좋아요 시 알림 로직 추가

- src/main/java/com/ttokttak/jellydiary/exception/message/SuccessMsg.java
- src/main/java/com/ttokttak/jellydiary/user/controller/UserController.java
- src/main/java/com/ttokttak/jellydiary/user/entity/UserEntity.java
- src/main/java/com/ttokttak/jellydiary/user/entity/UserStateEnum.java
- src/main/java/com/ttokttak/jellydiary/user/service/CustomOAuth2UserService.java
- src/main/java/com/ttokttak/jellydiary/user/service/UserService.java
- src/main/java/com/ttokttak/jellydiary/user/service/UserServiceImpl.java
[JD-81]Feat: 유저 회원 탈퇴 api 구현
- 회원탈퇴 진행시 유저 상태 INACTIVE로 변경, 알림 설정 모두 비활성화
[JD-81]: https://ttokttak.atlassian.net/browse/JD-81?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [JD-81]Feat: 유저 회원 탈퇴 api 구현

- src/main/java/com/ttokttak/jellydiary/notification/service/NotificationServiceImpl.java
[JD-301]
- notification service 코드에서 필요없는 주석과 줄바꿈을 제거하였습니다.
[JD-301]: https://ttokttak.atlassian.net/browse/JD-301?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [JD-301]Refactor: notification service 코드에서 필요없는 주석과 줄바꿈 제거

- src/main/java/com/ttokttak/jellydiary/sns/dto/SnsGetListResponseDto.java
- src/main/java/com/ttokttak/jellydiary/sns/mapper/SnsMapper.java
[JD-302]
- sns 조회 시 response에 diaryName를 추가하였습니다.
[JD-302]: https://ttokttak.atlassian.net/browse/JD-302?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [JD-302]Fix: sns 조회 시 response에 diaryName 추가

- src/main/java/com/ttokttak/jellydiary/exception/message/ErrorMsg.java
- src/main/java/com/ttokttak/jellydiary/exception/message/SuccessMsg.java
- src/main/java/com/ttokttak/jellydiary/notification/controller/NotificationController.java
- src/main/java/com/ttokttak/jellydiary/notification/service/NotificationService.java
- src/main/java/com/ttokttak/jellydiary/notification/service/NotificationServiceImpl.java
[JD-303]
- 알림 전체 삭제 api를 구현하였습니다.
[JD-303]: https://ttokttak.atlassian.net/browse/JD-303?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [JD-303]Fix: 알림 전체 삭제 api 구현

- src/main/java/com/ttokttak/jellydiary/diary/controller/DiaryProfileController.java
- src/main/java/com/ttokttak/jellydiary/diary/dto/DiaryProfileRequestDto.java
- src/main/java/com/ttokttak/jellydiary/diary/dto/DiaryProfileUpdateRequestDto.java
- src/main/java/com/ttokttak/jellydiary/diary/repository/DiaryUserRepository.java
- src/main/java/com/ttokttak/jellydiary/diary/service/DiaryProfileServiceImpl.java
- src/main/java/com/ttokttak/jellydiary/diary/service/DiaryUserServiceImpl.java
- src/main/java/com/ttokttak/jellydiary/exception/message/ErrorMsg.java
- src/main/java/com/ttokttak/jellydiary/feed/service/FeedServiceImpl.java
- src/main/java/com/ttokttak/jellydiary/follow/repository/FollowRepository.java
- src/main/java/com/ttokttak/jellydiary/notification/entity/NotificationType.java
[JD-304]Fix: 알림 코드 추가
- 다이어리 구독, 다이어리 참여 요청, 초대 승인, 초대 거절, 다이어리 삭제, 팔로워와 관련된 알림 코드를 추가했습니다.
[JD-304]: https://ttokttak.atlassian.net/browse/JD-304?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [JD-304]Fix: 알림 코드 추가 

- src/main/java/com/ttokttak/jellydiary/jwt/JWTUtil.java
- src/main/java/com/ttokttak/jellydiary/user/service/RefreshTokenService.java
- src/main/java/com/ttokttak/jellydiary/user/service/UserServiceImpl.java
[JD-306]Fix: Cookie 생성시 secure설정 활성화
[JD-306]: https://ttokttak.atlassian.net/browse/JD-306?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [JD-306]Fix: Cookie 생성시 secure설정 활성화

- src/main/java/com/ttokttak/jellydiary/user/dto/UserProfileDto.java
[JD-307]Fix: UserProfile의 NotificationSetting 항목 수정
[JD-307]: https://ttokttak.atlassian.net/browse/JD-307?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [JD-307]Fix: UserProfile의 NotificationSetting 항목 수정

- src/main/java/com/ttokttak/jellydiary/notification/entity/NotificationType.java
[JD-308]
- NotificationType에서 content 오타를 수정하였습니다.
[JD-308]: https://ttokttak.atlassian.net/browse/JD-308?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [JD-308]Refactor: NotificationType에서 content 오타 수정

- src/main/java/com/ttokttak/jellydiary/config/SecurityConfig.java
[JD-310]Fix: SpringSecurity config 수정
[JD-310]: https://ttokttak.atlassian.net/browse/JD-310?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [JD-310]Fix: SpringSecurity config 수정

- src/main/java/com/ttokttak/jellydiary/chat/controller/ChatMessageController.java
- src/main/java/com/ttokttak/jellydiary/chat/dto/ChatMessageListResponseDto.java
- src/main/java/com/ttokttak/jellydiary/chat/dto/ChatRoomRequestDto.java
- src/main/java/com/ttokttak/jellydiary/chat/dto/ChatRoomResponseDto.java
- src/main/java/com/ttokttak/jellydiary/chat/repository/ChatUserRepository.java
- src/main/java/com/ttokttak/jellydiary/chat/service/ChatMessageServiceImpl.java
- src/main/java/com/ttokttak/jellydiary/config/WebSocketConfig.java
- src/main/java/com/ttokttak/jellydiary/notification/entity/NotificationType.java
[JD-312]Fix: 알림 코드 추가 - DM
- 메시지 수신자에게 알림이 가도록 알림 코드를 추가했습니다.
[JD-312]: https://ttokttak.atlassian.net/browse/JD-312?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [JD-312]Fix: 알림 코드 추가 - DM

- src/main/java/com/ttokttak/jellydiary/user/service/UserServiceImpl.java
[JD-313]Fix: 유저 프로필 정보 수정시 들어온 userName이 기존의 userName과 같을 경우 중복확인 로직 pass
[JD-313]: https://ttokttak.atlassian.net/browse/JD-313?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [JD-313]Fix: 유저 프로필 정보 수정시 들어온 userName이 기존의 userName과 같을 경우 중복확인 로직 pass

- src/main/java/com/ttokttak/jellydiary/user/service/UserServiceImpl.java
[JD-314]Fix: 유저 닉네입 중복확인시 기존의 userName과 같을 경우 중복확인 로직 pass
[JD-314]: https://ttokttak.atlassian.net/browse/JD-314?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [JD-314]Fix: 유저 닉네입 중복확인시 기존의 userName과 같을 경우 중복확인 로직 pass

- src/main/java/com/ttokttak/jellydiary/config/CorsMvcConfig.java
[JD-315]Fix: CorsMvcConfig 수정
- SecurityConfig cors 설정과 동일하게 수정했습니다.
[JD-315]: https://ttokttak.atlassian.net/browse/JD-315?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [JD-315]Fix: CorsMvcConfig 수정

- README.md
- src/main/java/com/ttokttak/jellydiary/chat/dto/ChatMessageListResponseDto.java
- src/main/java/com/ttokttak/jellydiary/chat/dto/ChatRoomResponseDto.java
- src/main/java/com/ttokttak/jellydiary/chat/service/ChatMessageServiceImpl.java
- src/main/java/com/ttokttak/jellydiary/chat/service/ChatRoomServiceImpl.java
- src/main/java/com/ttokttak/jellydiary/comment/service/CommentServiceImpl.java
- src/main/java/com/ttokttak/jellydiary/diary/dto/DiaryProfileRequestDto.java
[JD-322]Docs: README.md 생성
[JD-323]Fix: ChatMessageListResponseDto, ChatRoomResponseDto 수정
[JD-322]: https://ttokttak.atlassian.net/browse/JD-322?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[JD-323]: https://ttokttak.atlassian.net/browse/JD-323?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [JD-322]Docs: README.md 생성, [JD-323]Fix: ChatMessageListResponseDto, ChatRoomResponseDto 수정

- src/main/java/com/ttokttak/jellydiary/chat/dto/ChatRoomResponseDto.java
- src/main/java/com/ttokttak/jellydiary/chat/repository/ChatUserRepository.java
- src/main/java/com/ttokttak/jellydiary/chat/service/ChatRoomServiceImpl.java
[JD-326]Fix: ChatRoomResponseDto에 chatUserCount(채팅방인원) 필드를 추가했습니다.
[JD-326]: https://ttokttak.atlassian.net/browse/JD-326?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [JD-326]Fix: ChatRoomResponseDto에 chatUserCount(채팅방인원) 필드 추가
