JellyDiary/JellyDiary_BE

- src/main/java/com/ttokttak/jellydiary/like/entity/LikeEntity.java
- src/main/java/com/ttokttak/jellydiary/like/entity/PostLikeCompositeKey.java
[JD-167]
- diaryPostId와 userId를 복합키로 구성하였습니다.
- like가 DB예약어 라서 기존 like 테이블 명을 post_like로 변경하여 진행하였습니다.
[JD-167]: https://ttokttak.atlassian.net/browse/JD-167?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [JD-167]Feat: post_like entity 생성

- src/main/java/com/ttokttak/jellydiary/follow/FollowCompositeKey.java
- src/main/java/com/ttokttak/jellydiary/follow/FollowEntity.java
[JD-168]
- Follow entity를 생성하였습니다.
- FollowEntity의 followRequestId와 followResponseId를 복합키로 구현하였습니다.
- Follow 테이블과 User 테이블의 관계는 중요하지 않고 
팔로우 하는 사람(followRequestId)과 팔로우 받는 사람(followReponseId) 과의 관계로 인해서 
Follow가 생성된다는 점에 주목하여 연관관계를 지우고 복합키를 사용하기로 결정하였습니다.
[JD-168]: https://ttokttak.atlassian.net/browse/JD-168?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [JD-168]Feat: Follow entity 생성

- src/main/java/com/ttokttak/jellydiary/like/entity/PostLikeCompositeKey.java
[JD-169]
- PostLikeCompositeKey에 equals()와 hashCode() 메서드 Overriding 추가하였습니다.
- 복합키 구현 시 equals()와 hashCode()를 필수로 구현해야 한다는 점을 인지하여 수정하였습니다.
[JD-169]: https://ttokttak.atlassian.net/browse/JD-169?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [JD-169]Fix: PostLikeCompositeKey에 equals(), hashCode() 추가

- src/main/java/com/ttokttak/jellydiary/util/entity/BaseTimeEntity.java
[JD-172] BaseTimeEntity 생성
createdAt, modifiedAt 컬럼이 들어가는 테이블이 많아 엔티티 클래스 분리하여 생성
[JD-172]: https://ttokttak.atlassian.net/browse/JD-172?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [JD-172]Feat: BaseTimeEntity 생성

- src/main/java/com/ttokttak/jellydiary/notification/entity/NotificationSettingEntity.java
[JD-185] @OneToOne 시 User -> UserEntity로 변경 및 불필요한 import 제거
- User entity의 class명이 User -> UserEntity 변경됨에 따라서 기존에 User 라고 되어 있는 부분들을 UserEntity로 변경하였습니다.
- 사용하지 않는 import를 제거하였습니다.
[JD-185]: https://ttokttak.atlassian.net/browse/JD-185?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [JD-185]Fix: @OneToOne 시 User -> UserEntity로 변경 및 불필요한 import 제거

- src/main/java/com/ttokttak/jellydiary/follow/FollowEntity.java
[JD-186] Follow entity에서 불필요한 기존 User import 제거
- User entity가 User -> UserEntity로 class명이 바뀜에 따라 사라진 User class를 import 하고 있던 FollowEntity class 에서 오류가 발생하여 해당 import를 제거하였습니다.
[JD-186]: https://ttokttak.atlassian.net/browse/JD-186?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [JD-186]Fix: Follow entity에서 불필요한 기존 User import 제거

- build.gradle
- src/main/java/com/ttokttak/jellydiary/config/SecurityConfig.java
- src/main/java/com/ttokttak/jellydiary/config/SwaggerConfig.java
- src/main/java/com/ttokttak/jellydiary/jwt/JWTFilter.java
[JD-192]
- Swagger 적용을 위해 dependency 추가 후 SwaggerConfig를 생성하였습니다.
- 현재 AccessToken이 Cookie에 저장되는 방식으로 구현되어 있어 추후 header로 변경시 :TODO를 수정해야 합니다.
[JD-199]
- JwtFilter Cookie가 null일 때도 반복문에서 Cookie를 찾고있기 때문에 오류가 발생하는 것으로 확인되어 해당 반복문을 if문으로 null이 아닐 시 반복문을 실행할 수 있도록 코드를 변경하였습니다.
[JD-200]
- Swagger 적용이 끝난 후 웹사이트에서 접속 테스트 시에 Swagger 문서인 /docs에 접근할 때도 JwtToken이 필요함을 발견하여 SecurityConfig에 .requestMatchers("/") -> .requestMatchers("**")로 변경하였습니다.
[JD-192]: https://ttokttak.atlassian.net/browse/JD-192?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[JD-199]: https://ttokttak.atlassian.net/browse/JD-199?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[JD-200]: …
> [JD-192]Swagger 적용 [JD-199]JwtFilter Cookie null일시 발생하는 에러 해결 [JD-200]SecurityConfig .requestMatchers / -> ** 변경

- src/main/java/com/ttokttak/jellydiary/diary/controller/DiaryProfileController.java
- src/main/java/com/ttokttak/jellydiary/diary/entity/DiaryProfileEntity.java
- src/main/java/com/ttokttak/jellydiary/diary/entity/DiaryUserEntity.java
- src/main/java/com/ttokttak/jellydiary/diary/repository/DiaryUserRepository.java
- src/main/java/com/ttokttak/jellydiary/diary/service/DiaryProfileService.java
- src/main/java/com/ttokttak/jellydiary/diary/service/DiaryProfileServiceImpl.java
- src/main/java/com/ttokttak/jellydiary/exception/message/ErrorMsg.java
[JD-203]Fix: DiaryProfileEntity, DiaryUserEntity 수정
- 엔티티에 생성자 어노테이션 추가하고, DiaryProfileEntity의 isDiaryDeleted 컬럼은 false로 초기화했습니다.
[JD-204]Fix: 다이어리 프로필 수정 api에서 누락된 부분 추가 구현
- 다이어리 프로필 수정 api에서 로그인한 회원이 다이어리 생성자인지 확인하는 코드가 누락되어, 이 부분을 추가했습니다.
[JD-203]: https://ttokttak.atlassian.net/browse/JD-203?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[JD-204]: https://ttokttak.atlassian.net/browse/JD-204?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [JD-203]Fix: DiaryProfileEntity, DiaryUserEntity 수정, [JD-204]Fix: 다이어리 프로필 수정 api에서 누락된 부분 추가 구현

- src/main/java/com/ttokttak/jellydiary/diary/controller/DiaryUserController.java
- src/main/java/com/ttokttak/jellydiary/diary/dto/DiaryUserResponseDto.java
- src/main/java/com/ttokttak/jellydiary/diary/mapper/DiaryUserMapper.java
- src/main/java/com/ttokttak/jellydiary/diary/repository/DiaryUserRepository.java
- src/main/java/com/ttokttak/jellydiary/diary/service/DiaryProfileServiceImpl.java
- src/main/java/com/ttokttak/jellydiary/diary/service/DiaryUserService.java
- src/main/java/com/ttokttak/jellydiary/diary/service/DiaryUserServiceImpl.java
- src/main/java/com/ttokttak/jellydiary/exception/message/SuccessMsg.java
[JD-205]Fix: DiaryUserRepository에서 findByDiaryIdAndUserId 메서드 리턴타입 수정
- DiaryUserEntity -> Optional<DiaryUserEntity로 수정
- 리턴타입 수정으로 DiaryProfileServiceImpl의 updateDiaryProfile 메서드도 null 처리 부분이 조금 수정되었습니다.
[JD-86]Feat: 다이어리 생성 / 참여 유저 리스트 조회 api 구현
- DiaryUserRole이 SUBSCRIBE가 아닐 경우 즉, READ / WRITE / CREATOR 이거나 또는 null인 경우 조회되도록 구현하였습니다.
- 왜 null인 경우 조회? -> 초대 요청 승인 대기 중인 유저는 DiaryUserRole이 null이기 때문에 이 유저도 조회되어야 하기 때문입니다.
[JD-205]: https://ttokttak.atlassian.net/browse/JD-205?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[JD-86]: https://ttokttak.atlassian.net/browse/JD-86?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [JD-205]Fix: DiaryUserRepository에서 findByDiaryIdAndUserId 메서드 리턴타입 수정, [JD-86]Feat: 다이어리 생성 / 참여 유저 리스트 조회 api 구현

- src/main/java/com/ttokttak/jellydiary/diary/controller/DiaryUserController.java
- src/main/java/com/ttokttak/jellydiary/diary/dto/DiaryUserRequestDto.java
- src/main/java/com/ttokttak/jellydiary/diary/mapper/DiaryUserMapper.java
- src/main/java/com/ttokttak/jellydiary/diary/service/DiaryProfileServiceImpl.java
- src/main/java/com/ttokttak/jellydiary/diary/service/DiaryUserService.java
- src/main/java/com/ttokttak/jellydiary/diary/service/DiaryUserServiceImpl.java
- src/main/java/com/ttokttak/jellydiary/exception/message/ErrorMsg.java
- src/main/java/com/ttokttak/jellydiary/exception/message/SuccessMsg.java
[JD-206]Fix: SuccessMsg에 다이어리 정보 조회 완료 enum 추가 후 getDiaryProfileInfo 리턴 메시지 변경
- 다이어리 정보 조회 완료 enum이 누락되어, 정보 조회 완료 시 정보 조회 완료 메시지가 아닌 생성 완료 메시지를 보내고 있다는 것을 발견했습니다. 그래서 SEARCH_DIARY_SUCCESS enum 추가 후 getDiaryProfileInfo 메서드의 리턴 메시지를 변경하였습니다.
[JD-207]Feat: 다이어리 유저 생성 api 구현
- 다이어리 생성자가 다른 사용자에게 초대 요청을 보내면 다이어리 유저가 생성됩니다. 이때 초대받은 사용자의 diaryRole은 READ, isInvited은 초대 승인 전이므로 false입니다.
[JD-206]: https://ttokttak.atlassian.net/browse/JD-206?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[JD-207]: https://ttokttak.atlassian.net/browse/JD-207?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [JD-206]Fix: SuccessMsg에 다이어리 정보 조회 완료 enum 추가 후 getDiaryProfileInfo 리턴 메시지 변경, [JD-207]Feat: 다이어리 유저 생성 api 구현

- src/main/java/com/ttokttak/jellydiary/diary/controller/DiaryUserController.java
- src/main/java/com/ttokttak/jellydiary/diary/dto/DiaryUserUpdateRoleRequestDto.java
- src/main/java/com/ttokttak/jellydiary/diary/entity/DiaryUserEntity.java
- src/main/java/com/ttokttak/jellydiary/diary/service/DiaryUserService.java
- src/main/java/com/ttokttak/jellydiary/diary/service/DiaryUserServiceImpl.java
- src/main/java/com/ttokttak/jellydiary/exception/message/ErrorMsg.java
- src/main/java/com/ttokttak/jellydiary/exception/message/SuccessMsg.java
[JD-87]Feat: 다이어리 유저들 role 수정 api 구현
- 다이어리 생성자는 다수의 참여자들의 role을 변경할 수 있습니다. 그래서 변경된 참여자들 정보를 list로 받아 role을 변경할 수 있도록 구현했습니다.
[JD-208]Feat: 다이어리 유저 isInvited 수정(초대 승인) api 구현
- 초대를 승인하면 isInvited 필드가 false에서 true로 변경되도록 구현했습니다.
[JD-209]Feat: 다이어리 유저 삭제 api 구현
- 다이어리 유저가 삭제되는 경우는 두 가지로 다이어리 생성자가 다른 참여자를 삭제하거나, 초대된 사용자가 초대를 거절하는 경우입니다. 이 두 가지 경우일 때 다이어리 유저를 삭제할 수 있도록 구현했습니다.
[JD-87]: https://ttokttak.atlassian.net/browse/JD-87?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[JD-208]: https://ttokttak.atlassian.net/browse/JD-208?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[JD-209]: https://ttokttak.atlassian.net/browse/JD-209?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0 …
> [JD-87]Feat: 다이어리 유저들 role 수정 api 구현, [JD-208]Feat: 다이어리 유저 isInvited 수정(초대 승인) api 구현, [JD-209]Feat: 다이어리 유저 삭제 api 구현

- src/main/java/com/ttokttak/jellydiary/diary/controller/DiaryUserController.java
- src/main/java/com/ttokttak/jellydiary/diary/service/DiaryUserService.java
- src/main/java/com/ttokttak/jellydiary/diary/service/DiaryUserServiceImpl.java
- src/main/java/com/ttokttak/jellydiary/exception/message/ErrorMsg.java
- src/main/java/com/ttokttak/jellydiary/exception/message/SuccessMsg.java
[JD-126]Feat: 다이어리 유저(권한) 조회 api 구현
- 다이어리 페이지에 접근할 때, 해당 다이어리에서 현재 로그인한 사용자의 정보를 조회하는 API입니다.
[JD-126]: https://ttokttak.atlassian.net/browse/JD-126?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [JD-126]Feat: 다이어리 유저(권한) 조회 api 구현

- src/main/java/com/ttokttak/jellydiary/diary/entity/DiaryUserEntity.java
- src/main/java/com/ttokttak/jellydiary/diary/service/DiaryUserServiceImpl.java
- src/main/java/com/ttokttak/jellydiary/exception/message/ErrorMsg.java
[JD-211]Fix: 다이어리 유저 생성 api 수정 - 구독 시에도 다이어리 유저가 생성되도록 변경
- 다이어리 유저는 다이어리 생성자가 다른 사용자를 다이어리에 초대하거나, 다이어리 생성자가 아닌 사용자가 다이어리를 구독할 때 생성됩니다.
- 다이어리 생성자가 초대한 사용자가 이미 해당 다이어리를 구독하고 있다면, 새로운 다이어리 유저를 생성하는 대신, isInvited 컬럼이 null에서 false로 변경되도록 구현했습니다.
[JD-211]: https://ttokttak.atlassian.net/browse/JD-211?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [JD-211]Fix: 다이어리 유저 생성 api 수정 - 구독 시에도 다이어리 유저가 생성되도록 변경

- src/main/java/com/ttokttak/jellydiary/diary/controller/DiaryUserController.java
- src/main/java/com/ttokttak/jellydiary/diary/service/DiaryUserService.java
- src/main/java/com/ttokttak/jellydiary/diary/service/DiaryUserServiceImpl.java
- src/main/java/com/ttokttak/jellydiary/exception/message/ErrorMsg.java
[JD-213]Fix: 다이어리 유저 isInvited 수정(초대 승인) api 수정
- diaryUserId의 userId가 로그인한 회원의 userId와 일치할 때만 수정(초대 승인)되도록 코드를 추가하였습니다.
[JD-213]: https://ttokttak.atlassian.net/browse/JD-213?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [JD-213]Fix: 다이어리 유저 isInvited 수정(초대 승인) api 수정

- src/main/java/com/ttokttak/jellydiary/diarypost/controller/DiaryPostController.java
- src/main/java/com/ttokttak/jellydiary/diarypost/entity/DiaryPostEntity.java
- src/main/java/com/ttokttak/jellydiary/diarypost/repository/DiaryPostImgRepository.java
- src/main/java/com/ttokttak/jellydiary/diarypost/service/DiaryPostService.java
- src/main/java/com/ttokttak/jellydiary/diarypost/service/DiaryPostServiceImpl.java
- src/main/java/com/ttokttak/jellydiary/exception/message/ErrorMsg.java
- src/main/java/com/ttokttak/jellydiary/exception/message/SuccessMsg.java
[JD-215]
- 이미지는 아직 s3가 연결되어 있지 않은 관계로 s3 관련 코드만 제외하여 구현하였습니다.
- 이미지는 클라이언트에서 삭제한 이미지의 Id와 새로 추가한 이미지를 각각의 리스트로 받아서 구현하였습니다.
- 이미지 처리 로직 중 생성과 중복되는 코드가 있어 해당 로직은 따로 메서드를 분류하였습니다.
[JD-215]: https://ttokttak.atlassian.net/browse/JD-215?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [JD-215]Feat: 게시글 생성 api 구현

- src/main/java/com/ttokttak/jellydiary/diarypost/entity/DiaryPostImgEntity.java
- src/main/java/com/ttokttak/jellydiary/diarypost/mapper/DiaryPostImgMapper.java
- src/main/java/com/ttokttak/jellydiary/diarypost/service/DiaryPostServiceImpl.java
- src/main/java/com/ttokttak/jellydiary/exception/message/SuccessMsg.java
[JD-217]
- softDelete를 위하여 isDeleted 필드를 DiaryPostImg에 추가하고 @Where과 @SQLDelete 를 추가해주었습니다.
[JD-217]: https://ttokttak.atlassian.net/browse/JD-217?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [JD-217]Fix: DiaryPostImg에 isDeleted 추가 및 softDelete 처리

- src/main/java/com/ttokttak/jellydiary/diary/repository/DiaryUserRepository.java
- src/main/java/com/ttokttak/jellydiary/diary/service/DiaryUserServiceImpl.java
구독자면서 초대받은 사용자도 조회될 수 있도록 변경하였습니다. 
api 결과로 다이어리 생성자, 참여자(READ/WRITE), 초대 받은 구독자가 조회됩니다.
> [JD-218]Fix: 다이어리 생성/참여 유저 리스트 조회 api 수정

- src/main/java/com/ttokttak/jellydiary/diary/controller/DiaryProfileController.java
- src/main/java/com/ttokttak/jellydiary/diary/entity/DiaryProfileEntity.java
- src/main/java/com/ttokttak/jellydiary/diary/service/DiaryProfileService.java
- src/main/java/com/ttokttak/jellydiary/diary/service/DiaryProfileServiceImpl.java
- src/main/java/com/ttokttak/jellydiary/diary/service/DiaryUserServiceImpl.java
- src/main/java/com/ttokttak/jellydiary/exception/message/ErrorMsg.java
- src/main/java/com/ttokttak/jellydiary/exception/message/SuccessMsg.java
[JD-226]Feat: 다이어리 삭제 api 구현
- 다이어리 삭제 API를 구현하고, 삭제된 다이어리를 조회, 수정, 또는 재삭제하려고 시도했을 때 '삭제된 다이어리입니다'라는 404 에러 메시지가 반환되도록 설정했습니다.
[JD-226]: https://ttokttak.atlassian.net/browse/JD-226?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [JD-226]Feat: 다이어리 삭제 api 구현

- src/main/java/com/ttokttak/jellydiary/exception/message/SuccessMsg.java
- src/main/java/com/ttokttak/jellydiary/feed/controller/FeedController.java
- src/main/java/com/ttokttak/jellydiary/feed/dto/TargetUserInfoResponseDto.java
- src/main/java/com/ttokttak/jellydiary/feed/mapper/FeedMapper.java
- src/main/java/com/ttokttak/jellydiary/feed/service/FeedService.java
- src/main/java/com/ttokttak/jellydiary/feed/service/FeedServiceImpl.java
- src/main/java/com/ttokttak/jellydiary/follow/entity/FollowCompositeKey.java
- src/main/java/com/ttokttak/jellydiary/follow/entity/FollowEntity.java
- src/main/java/com/ttokttak/jellydiary/follow/repository/FollowRepository.java
[JD-130]Feat: 타겟 유저 정보 조회 api 구현
- 타겟 유저 정보를 조회하면, 해당 유저의 이름과 소개 등의 프로필 정보와 함께 팔로워 수 및 팔로우 수를 얻을 수 있도록 구현했습니다.
[JD-130]: https://ttokttak.atlassian.net/browse/JD-130?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [JD-130]Feat: 타겟 유저 정보 조회 api 구현

- src/main/java/com/ttokttak/jellydiary/follow/entity/FollowEntity.java
[JD-228]Fix: FollowEntity 수정 - @ ManyToOne 관계와 필드 등 누락된 부분 추가
- FollowEntity에 @ ManyToOne 관계와 FollowRequest와 FollowResponse 필드를 추가했습니다.
-  외래 키를 기본 키의 일부로 매핑할 때 사용되는 @ MapsId를 추가했습니다. 이를 통해 FollowEntity의 기본 키와 연관된 UserEntity 필드를 정확히 매핑할 수 있습니다.
[JD-228]: https://ttokttak.atlassian.net/browse/JD-228?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [JD-228]Fix: FollowEntity 수정 - @ManyToOne 관계와 필드 등 누락된 부분 추가

- src/main/java/com/ttokttak/jellydiary/exception/message/SuccessMsg.java
- src/main/java/com/ttokttak/jellydiary/feed/controller/FeedController.java
- src/main/java/com/ttokttak/jellydiary/feed/dto/TargetUserFollowersDto.java
- src/main/java/com/ttokttak/jellydiary/feed/mapper/FeedMapper.java
- src/main/java/com/ttokttak/jellydiary/feed/service/FeedService.java
- src/main/java/com/ttokttak/jellydiary/feed/service/FeedServiceImpl.java
- src/main/java/com/ttokttak/jellydiary/follow/repository/FollowRepository.java
[JD-132]Feat: 타겟 유저의 팔로워 리스트 조회 api 구현
- 타겟 유저를 팔로우 하고 있는 유저(팔로워)들의 프로필을 조회하는 api입니다.
[JD-132]: https://ttokttak.atlassian.net/browse/JD-132?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [JD-132]Feat: 타겟 유저의 팔로워 리스트 조회 api 구현

- src/main/java/com/ttokttak/jellydiary/exception/message/ErrorMsg.java
- src/main/java/com/ttokttak/jellydiary/exception/message/SuccessMsg.java
- src/main/java/com/ttokttak/jellydiary/like/controller/PostLikeController.java
- src/main/java/com/ttokttak/jellydiary/like/service/PostLikeService.java
- src/main/java/com/ttokttak/jellydiary/like/service/PostLikeServiceImpl.java
[JD-231]
- 게시글 좋아요 취소 api 를 호출 시 좋아요 테이블에 해당 정보가 존재하면 삭제, 존재하지 않는다면 예외처리를 하도록 구현하였습니다.
[JD-231]: https://ttokttak.atlassian.net/browse/JD-231?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [JD-231]Feat: 게시글 좋아요 취소 api 구현

- src/main/java/com/ttokttak/jellydiary/exception/message/ErrorMsg.java
- src/main/java/com/ttokttak/jellydiary/like/service/PostLikeServiceImpl.java
[JD-233]
- PostLike 테이블에 해당 행이 존재하지 않는다면 예외처리를 진행하였는데 "이미 취소된 게시글이다"라는 말보다 "이 게시물은 아직 좋아요를 하지 않았습니다."가 자연스럽다 판단하여 변경하였습니다.
[JD-233]: https://ttokttak.atlassian.net/browse/JD-233?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [JD-233]Fix: 게시물 좋아요 취소 연속 요청시 에러 문구 수정

- src/main/java/com/ttokttak/jellydiary/feed/controller/FeedController.java
- src/main/java/com/ttokttak/jellydiary/feed/dto/TargetUserInfoResponseDto.java
- src/main/java/com/ttokttak/jellydiary/feed/mapper/FeedMapper.java
- src/main/java/com/ttokttak/jellydiary/feed/service/FeedService.java
- src/main/java/com/ttokttak/jellydiary/feed/service/FeedServiceImpl.java
- src/main/java/com/ttokttak/jellydiary/follow/repository/FollowRepository.java
[JD-232]Fix: 타겟 유저 정보 조회 api 수정 
- responseDto에 타겟 유저를 팔로우하고 있는지 확인할 수 있는 필드(followStatus)를 추가했습니다.
[JD-232]: https://ttokttak.atlassian.net/browse/JD-232?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [JD-232]Fix: 타겟 유저 정보 조회 api 수정 - 타겟 유저를 팔로우하고 있는지 확인할 수 있는 필드 추가

- src/main/java/com/ttokttak/jellydiary/diarypost/repository/DiaryPostImgRepository.java
- src/main/java/com/ttokttak/jellydiary/diarypost/repository/DiaryPostRepository.java
- src/main/java/com/ttokttak/jellydiary/exception/message/SuccessMsg.java
- src/main/java/com/ttokttak/jellydiary/feed/controller/FeedController.java
- src/main/java/com/ttokttak/jellydiary/feed/dto/TargetUserFeedListResponseDto.java
- src/main/java/com/ttokttak/jellydiary/feed/dto/TargetUserFeedResponseDto.java
- src/main/java/com/ttokttak/jellydiary/feed/mapper/FeedMapper.java
- src/main/java/com/ttokttak/jellydiary/feed/service/FeedService.java
- src/main/java/com/ttokttak/jellydiary/feed/service/FeedServiceImpl.java
[JD-131]Fix: 타겟 유저의 피드 리스트 조회  api 구현
- 타겟 유저의 피드에 접근하면 해당 유저가 작성한 게시물을 볼 수 있습니다. 
다만, 게시물이 비공개 상태인 경우에는 해당 유저가 로그인한 회원이 아니라면 볼 수 없으며, 삭제된 게시물은 모두 접근이 불가능합니다.
[JD-131]: https://ttokttak.atlassian.net/browse/JD-131?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [JD-131]Fix: 타겟 유저의 피드 리스트 조회  api 구현

- src/main/java/com/ttokttak/jellydiary/diary/service/DiaryProfileServiceImpl.java
- src/main/java/com/ttokttak/jellydiary/diary/service/DiaryUserServiceImpl.java
- src/main/java/com/ttokttak/jellydiary/feed/service/FeedServiceImpl.java
[JD-239]Fix: 조회 메서드 @ Transactional 어노테이션 삭제
- diaryProfileServiceImpl, diaryUserServiceImpl, FeedServiceImpl 에서 조회 메서드일 경우 @ Transactional 어노테이션을 삭제했습니다.
[JD-239]: https://ttokttak.atlassian.net/browse/JD-239?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [JD-239]Fix: 조회 메서드 @ Transactional 어노테이션 삭제

- src/main/java/com/ttokttak/jellydiary/comment/controller/CommentController.java
- src/main/java/com/ttokttak/jellydiary/comment/dto/CommentMapper.java
- src/main/java/com/ttokttak/jellydiary/comment/dto/ReplyCommentGetListResponseDto.java
- src/main/java/com/ttokttak/jellydiary/comment/repository/CommentRepository.java
- src/main/java/com/ttokttak/jellydiary/comment/service/CommentService.java
- src/main/java/com/ttokttak/jellydiary/comment/service/CommentServiceImpl.java
- src/main/java/com/ttokttak/jellydiary/exception/message/SuccessMsg.java
[JD-240] 
- parent가 null이 아니며 PathVariable로 들어온 commentId와 postId가 일치하는 답글들만 리스트로 조회될 수 있도록 특정 댓글의 답글 리스트 조회를 구현하였습니다.
[JD-240]: https://ttokttak.atlassian.net/browse/JD-240?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [JD-240]Feat: 특정 댓글의 답글 리스트 조회 api 구현

- src/main/java/com/ttokttak/jellydiary/diarypost/dto/DiaryPostImgListResponseDto.java
- src/main/java/com/ttokttak/jellydiary/diarypost/mapper/DiaryPostImgMapper.java
[JD-241]
- 게시물 response에서 imgId가 누락되었다는 사실을 프론트에서 발견하여 해당 부분의 response에 imgId를 추가하였습니다.
[JD-241]: https://ttokttak.atlassian.net/browse/JD-241?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [JD-241]Fix: 게시물 작성, 수정, 조회 시 Response에 imgId 누락된 것 추가

- src/main/java/com/ttokttak/jellydiary/feed/controller/FeedController.java
- src/main/java/com/ttokttak/jellydiary/feed/dto/TargetUserFollowersDto.java
- src/main/java/com/ttokttak/jellydiary/feed/mapper/FeedMapper.java
- src/main/java/com/ttokttak/jellydiary/feed/service/FeedService.java
- src/main/java/com/ttokttak/jellydiary/feed/service/FeedServiceImpl.java
[JD-242]Fix: 타겟 유저의 팔로워 리스트, 팔로우 리스트 ResponseDto에 followStatus 필드 추가
- 타겟 유저의 팔로워 리스트와 팔로우 리스트를 조회할 때, 로그인한 유저와 목록에 있는 다른 유저들 간의 팔로우 상태를 알 수 있도록 followStatus 필드를 추가했습니다.
[JD-242]: https://ttokttak.atlassian.net/browse/JD-242?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [JD-242]Fix: 타겟 유저의 팔로워 리스트, 팔로우 리스트 ResponseDto에 followStatus 필드 추가

- build.gradle
- src/main/java/com/ttokttak/jellydiary/config/S3Config.java
- src/main/java/com/ttokttak/jellydiary/exception/message/ErrorMsg.java
- src/main/java/com/ttokttak/jellydiary/exception/message/SuccessMsg.java
- src/main/java/com/ttokttak/jellydiary/user/controller/UserController.java
- src/main/java/com/ttokttak/jellydiary/user/entity/UserEntity.java
- src/main/java/com/ttokttak/jellydiary/user/service/UserService.java
- src/main/java/com/ttokttak/jellydiary/user/service/UserServiceImpl.java
- src/main/java/com/ttokttak/jellydiary/util/S3Uploader.java
[JD-79]Feat: 유저 프로필 이미지 변경 api 구현
AWS SDK for Java v2를 이용하여 구현
- 기존이미지 null여부 / 새로운 이미지 null여부에 따라 로직처리를 해주었음
=> 기존 이미지 null, 새로운 이미지 null = 변동 X
=> 기존 이미지 null, 새로운 이미지 O = 새로운 이미지 업로드 후, S3 URL을 DB에 저장
=> 기존 이미지 O, 새로운 이미지 null = 기존 이미지 URL에서 S3 경로 추출후 S3에서 기존 이미지 삭제 후 DB에 null로 저장
=> 기존 이미지 O, 새로운 이미지 O = 기존 이미지 URL에서 S3 경로 추출후 S3에서 기존 이미지 삭제 + 새로운 이미지 업로드 후, S3 URL을 DB에 저장
[JD-79]: https://ttokttak.atlassian.net/browse/JD-79?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [JD-79]Feat: 유저 프로필 이미지 변경 api 구현

- src/main/java/com/ttokttak/jellydiary/util/service/SearchServiceImpl.java
[JD-246]
- 다이어리 유저 테이블에 존재하며 권한이 CREATOR가 아니면 무조건 true로 설정했던 부분을 diaryUserEntity.getIsInvited()로 변경하여 해당 이슈를 해결하였습니다.
[JD-246]: https://ttokttak.atlassian.net/browse/JD-246?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [JD-246]Fix: 다이어리 참여자 추가 시 사용자 검색 api 에서 구독자에 경우 isInvited가 ture로 response되는 문제 해결

- src/main/java/com/ttokttak/jellydiary/exception/message/ErrorMsg.java
- src/main/java/com/ttokttak/jellydiary/exception/message/SuccessMsg.java
- src/main/java/com/ttokttak/jellydiary/user/controller/UserController.java
- src/main/java/com/ttokttak/jellydiary/user/dto/UserNameCheckRequestDto.java
- src/main/java/com/ttokttak/jellydiary/user/repository/UserRepository.java
- src/main/java/com/ttokttak/jellydiary/user/service/UserService.java
- src/main/java/com/ttokttak/jellydiary/user/service/UserServiceImpl.java
[JD-247]Feat: 유저 이름 중복 조회 api 구현
이름 형식 validation 설정
- 이름은 2~15자의 한글, 영문 대소문자, 숫자 및 언더바(_), 점(.)만 사용 가능
이름 중복 확인
- 유저 테이블 내부에서 중복되는 userName이 있는지 확인
[JD-247]: https://ttokttak.atlassian.net/browse/JD-247?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [JD-247]Feat: 유저 이름 중복 조회 api 구현

- src/main/java/com/ttokttak/jellydiary/comment/dto/CommentGetCommentInfoDto.java
- src/main/java/com/ttokttak/jellydiary/comment/dto/CommentGetListResponseDto.java
- src/main/java/com/ttokttak/jellydiary/comment/dto/CommentMapper.java
- src/main/java/com/ttokttak/jellydiary/comment/service/CommentServiceImpl.java
- src/main/java/com/ttokttak/jellydiary/diarypost/service/DiaryPostServiceImpl.java
[JD-256]
- 프론트 측에서 특정 게시물에 댓글 리스트 조회 api 에 response를 각 리스트마다 그에 해당하는 답글 개수를 추가하여 반환해달라고 요청하셔서 해당 부분을 적용하였습니다.
[JD-256]: https://ttokttak.atlassian.net/browse/JD-256?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [JD-256]Feat: 게시물 댓글 리스트 조회에서 response에 해당 댓글에 작성된 답글 개수 추가

- src/main/java/com/ttokttak/jellydiary/comment/service/CommentServiceImpl.java
[JD-257]
- 특정 댓글의 답글 리스트 조회 api를 실행하면 userId와 userName이 해당 답글을 작성한 사용자의 정보가 아닌 지금 api를 요청한 사용자의 정보로 잘못 response되는 것을 발견하여 해당 부분을 수정하였습니다.
[JD-257]: https://ttokttak.atlassian.net/browse/JD-257?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [JD-257]Fix: 특정 댓글의 답글 리스트 조회 시 response에 user정보가 api 요청자의 정보로 잘못 response 되는 부분 수정

- src/main/java/com/ttokttak/jellydiary/diarypost/entity/DiaryPostEntity.java
- src/main/java/com/ttokttak/jellydiary/diarypost/service/DiaryPostServiceImpl.java
- src/main/java/com/ttokttak/jellydiary/sns/controller/SnsController.java
- src/main/java/com/ttokttak/jellydiary/sns/dto/SnsGetListResponseDto.java
- src/main/java/com/ttokttak/jellydiary/sns/service/SnsService.java
- src/main/java/com/ttokttak/jellydiary/sns/service/SnsServiceImpl.java
[JD-259]
-  게시물 수정 시 weather에 null값이나 빈 값이 request되면 오류가 발생하였고, update시에 실행되는 메서드에 null값과 isBlank 여부를 확인하여 적절하게 처리함으로써 해당 오류를 해결하였습니다.
[JD-259]: https://ttokttak.atlassian.net/browse/JD-259?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [JD-259]Fix: 게시물 수정 시 weather에 null값이나 빈 값이 request되면 발생하는 오류 해결

- src/main/java/com/ttokttak/jellydiary/user/entity/UserEntity.java
- src/main/java/com/ttokttak/jellydiary/user/service/CustomOAuth2UserService.java
[JD-261]Fix: 유저 생성시 유저 알림 세팅 객체 생성
유저 객체가 생성될 경우 자동으로 유저 알림 객체가 생성되도록 UserEntity에 콜백 메서드 추가
@PostPersist
: 엔티티가 데이터베이스에 저장된 직후에 실행되는 콜백 메서드를 정의할 때 사용하는 어노테이션
=> UserEntity 인스턴스가 데이터베이스에 저장된 후에 자동으로 실행되어, 저장된 엔티티의 ID를 출력하거나 다른 초기화 작업을 수행
[JD-261]: https://ttokttak.atlassian.net/browse/JD-261?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [JD-261]Fix: 유저 생성시 유저 알림 세팅 객체 생성

- src/main/java/com/ttokttak/jellydiary/chat/controller/ChatRoomController.java
- src/main/java/com/ttokttak/jellydiary/chat/dto/ChatRoomRequestDto.java
- src/main/java/com/ttokttak/jellydiary/chat/dto/ChatRoomTypeEnum.java
- src/main/java/com/ttokttak/jellydiary/chat/entity/ChatRoomEntity.java
- src/main/java/com/ttokttak/jellydiary/chat/entity/ChatUserEntity.java
- src/main/java/com/ttokttak/jellydiary/chat/repository/ChatRoomRepository.java
- src/main/java/com/ttokttak/jellydiary/chat/repository/ChatUserRepository.java
- src/main/java/com/ttokttak/jellydiary/chat/service/ChatRoomService.java
- src/main/java/com/ttokttak/jellydiary/chat/service/ChatRoomServiceImpl.java
- src/main/java/com/ttokttak/jellydiary/exception/message/ErrorMsg.java
- src/main/java/com/ttokttak/jellydiary/exception/message/SuccessMsg.java
[JD-262]Feat: 채팅방 아이디 조회 api 구현
- 채팅 메시지를 보낼 때 채팅방 아이디를 함께 보내주기 위해 사용될 채팅방 아이디를 조회하는 api 입니다. 
- 그룹 채팅: 다이어리 ID를 받아 해당 다이어리 생성 시 함께 생성된 채팅방 ID를 반환합니다. 다이어리에 참여하고 있지 않다면 "채팅방 참여자가 아니므로 채팅에 참여할 수 없다"는 오류 메시지를 반환합니다.
- 개인 채팅: 두 사용자 간의 채팅방이 존재하는지 먼저 조회합니다. 채팅방이 이미 존재한다면 해당 채팅방 ID를 반환하고, 그렇지 않다면 새로운 채팅방을 생성한 후 해당 채팅방 ID를 반환합니다. 단, 사용자가 자기 자신과 채팅하려고 한다면 이는 허용되지 않으며, "자기 자신과 채팅은 불가능합니다"라는 오류 메시지를 반환합니다.
[JD-262]: https://ttokttak.atlassian.net/browse/JD-262?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [JD-262]Feat: 채팅방 아이디 조회 api 구현

- src/main/java/com/ttokttak/jellydiary/diary/entity/DiaryProfileEntity.java
- src/main/java/com/ttokttak/jellydiary/diary/service/DiaryProfileServiceImpl.java
[JD-263]Fix: 다이어리 생성 시 채팅방도 함께 생성되도록 코드 추가
- 다이어리 생성 시 채팅방도 함께 생성되도록 코드를 추가했습니다. 생성된 채팅방 id는 다이어리 프로필 정보에 저장됩니다.
[JD-263]: https://ttokttak.atlassian.net/browse/JD-263?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [JD-263]Fix: 다이어리 생성 시 채팅방도 함께 생성되도록 코드 추가

- src/main/java/com/ttokttak/jellydiary/chat/repository/ChatUserRepository.java
- src/main/java/com/ttokttak/jellydiary/diary/service/DiaryUserServiceImpl.java
[JD-265]Fix: 다이어리에서 참여자가 삭제되면, 해당 다이어리의 그룹 채팅방에서도 삭제되도록 수정
- 다이어리에서 참여자가 삭제되면(생성자가 참여자 삭제, 참여자가 다이어리 참여 삭제), 해당 다이어리의 그룹 채팅방에서도 삭제되도록 수정했습니다.
[JD-265]: https://ttokttak.atlassian.net/browse/JD-265?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [JD-265]Fix: 다이어리에서 참여자가 삭제되면, 해당 다이어리의 그룹 채팅방에서도 삭제되도록 수정

- src/main/java/com/ttokttak/jellydiary/diarypost/controller/DiaryPostController.java
- src/main/java/com/ttokttak/jellydiary/diarypost/service/DiaryPostService.java
- src/main/java/com/ttokttak/jellydiary/diarypost/service/DiaryPostServiceImpl.java
- src/main/java/com/ttokttak/jellydiary/util/S3Uploader.java
[JD-266]
- 프론트에서 null값과 빈 배열을 보낼 시 각 null값과 빈 배열에 대한 파일이 s3에 업로드 되는 것을 확인하여 관련 코드를 살펴보다가 DiaryPostService 내 img 메서드에서 throws IOException이 누락되었다는 것을 발견하게 되었으며, 이를 수정하였습니다.
[JD-266]: https://ttokttak.atlassian.net/browse/JD-266?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [JD-266]Fix: DiaryPostService 내 img 메서드에서 누락된 throws IOException 추가

- src/main/java/com/ttokttak/jellydiary/diarypost/controller/DiaryPostController.java
- src/main/java/com/ttokttak/jellydiary/diarypost/entity/DiaryPostEntity.java
- src/main/java/com/ttokttak/jellydiary/diarypost/mapper/DiaryPostImgMapper.java
- src/main/java/com/ttokttak/jellydiary/diarypost/mapper/DiaryPostMapper.java
- src/main/java/com/ttokttak/jellydiary/diarypost/service/DiaryPostService.java
- src/main/java/com/ttokttak/jellydiary/diarypost/service/DiaryPostServiceImpl.java
[JD-268]
- 게시물 수정 시 null을 넣게 되면 기존값이 등록되도록 mapstruct를 사용하여 patch에 맞게 null 처리해주었습니다.
- 필요없는 throws IOException를 제거하였습니다.
[JD-268]: https://ttokttak.atlassian.net/browse/JD-268?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [JD-268]Fix: 게시물 수정 시 mapstruct를 사용하여 patch에 맞게 null 처리 및 필요없는 throws IOException제거

- src/main/java/com/ttokttak/jellydiary/diarypost/service/DiaryPostServiceImpl.java
[JD-269]
- 게시물 이미지 수정 시 null인지 여부 확인하는 로직이 누락된 것을 확인하여 if문으로 null이 아닐 때 이미지를 생성할 수 있도록 추가하였습니다.
[JD-269]: https://ttokttak.atlassian.net/browse/JD-269?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [JD-269]Fix: 게시물 이미지 수정 시 null처리 추가

- src/main/java/com/ttokttak/jellydiary/diarypost/entity/DiaryPostEntity.java
- src/main/java/com/ttokttak/jellydiary/diarypost/mapper/DiaryPostMapper.java
- src/main/java/com/ttokttak/jellydiary/diarypost/service/DiaryPostServiceImpl.java
[JD-270]
- 게시물 상세 조회 api 시 response에 userId가 현재 로그인된 사용자의 Id로 출력되어 해당 게시물을 작성한 사람의 id를 response해줄 수 있도록 수정하였습니다.
[JD-270]: https://ttokttak.atlassian.net/browse/JD-270?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [JD-270]Fix: 게시물 상세 조회 api 시 response에 userId가 현재 로그인된 사용자의 Id로 뜨는 오류 해결

- src/main/java/com/ttokttak/jellydiary/chat/controller/ChatRoomController.java
- src/main/java/com/ttokttak/jellydiary/chat/dto/ChatRoomResponseDto.java
- src/main/java/com/ttokttak/jellydiary/chat/entity/ChatMessageEntity.java
- src/main/java/com/ttokttak/jellydiary/chat/repository/ChatMessageRepository.java
- src/main/java/com/ttokttak/jellydiary/chat/repository/ChatUserRepository.java
- src/main/java/com/ttokttak/jellydiary/chat/service/ChatMessageServiceImpl.java
- src/main/java/com/ttokttak/jellydiary/chat/service/ChatRoomService.java
- src/main/java/com/ttokttak/jellydiary/chat/service/ChatRoomServiceImpl.java
- src/main/java/com/ttokttak/jellydiary/exception/message/SuccessMsg.java
[JD-272]Feat: 나의 채팅 리스트 조회 api 구현
- 이 api는 로그인한 사용자의 채팅 목록을 조회합니다. responseDto에는 그룹 채팅의 경우 다이어리 이름과 다이어리 프로필 사진, 개인 채팅의 경우 상대방의 이름과 상대방 프로필 사진이 포함됩니다. 또한 모든 채팅 유형에서는 채팅방 아이디와 가장 최신 메시지가 포함됩니다. 최신 메시지가 없는 경우 "새로운 채팅방이 생성되었습니다. 첫 번째 메시지를 보내보세요."라는 메시지가 포함됩니다.
[JD-272]: https://ttokttak.atlassian.net/browse/JD-272?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [JD-272]Feat: 나의 채팅 리스트 조회 api 구현

- src/main/java/com/ttokttak/jellydiary/diarypost/repository/DiaryPostImgRepository.java
- src/main/java/com/ttokttak/jellydiary/diarypost/repository/DiaryPostRepositoryCustom.java
- src/main/java/com/ttokttak/jellydiary/diarypost/repository/DiaryPostRepositoryCustomImpl.java
- src/main/java/com/ttokttak/jellydiary/sns/dto/SnsGetResponseDto.java
- src/main/java/com/ttokttak/jellydiary/sns/mapper/SnsMapper.java
- src/main/java/com/ttokttak/jellydiary/sns/service/SnsServiceImpl.java
[JD-275]
- Slice를 활용한 페이지네이션으로 sns 게시물 리스트 조회를 구현하였습니다.
- Page에 경우 조회 쿼리가 추가로 나가기 때문에 성능을 고려하여 Slice를 구현하기로 결정하였고, 복잡한 동적쿼리는 QueryDsl을 사용하였습니다.
[JD-275]: https://ttokttak.atlassian.net/browse/JD-275?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [JD-275]Feat: sns 게시물 리스트 조회 Slice를 활용한 페이지네이션 구현 완료

- src/main/java/com/ttokttak/jellydiary/sns/service/SnsServiceImpl.java
[JD-276]
- sns 게시물 리스트 조회 시 hasNext가 항상 false로 response되는 문제를 해결하였습니다.
- 필요하지 않은 if문을 삭제하고 postOrderByCreatedAtDesc의 결과에 포함된 hasNext()를 responseDto에 넣어줌으로써 해결하였습니다.
[JD-276]: https://ttokttak.atlassian.net/browse/JD-276?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [JD-276]Fix: sns 게시물 리스트 조회 시 hasNext가 항상 false로 response되는 문제 해결

- src/main/java/com/ttokttak/jellydiary/chat/controller/ChatRoomController.java
- src/main/java/com/ttokttak/jellydiary/chat/dto/ChatMessageResponseDto.java
- src/main/java/com/ttokttak/jellydiary/chat/mapper/ChatMessageMapper.java
- src/main/java/com/ttokttak/jellydiary/chat/service/ChatMessageService.java
- src/main/java/com/ttokttak/jellydiary/chat/service/ChatMessageServiceImpl.java
- src/main/java/com/ttokttak/jellydiary/exception/message/SuccessMsg.java
[JD-278]Feat: 채팅 내역 상세 조회 api 구현
- 입력받은 채팅방의 메시지들을 조회하는 api입니다. 최신 메시지의 30개를 리스트에 담아 내보냅니다.
[JD-278]: https://ttokttak.atlassian.net/browse/JD-278?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [JD-278]Feat: 채팅 내역 상세 조회 api 구현

- src/main/java/com/ttokttak/jellydiary/chat/controller/ChatRoomController.java
- src/main/java/com/ttokttak/jellydiary/chat/dto/ChatMessageListResponseDto.java
- src/main/java/com/ttokttak/jellydiary/chat/repository/ChatMessageRepository.java
- src/main/java/com/ttokttak/jellydiary/chat/service/ChatMessageService.java
- src/main/java/com/ttokttak/jellydiary/chat/service/ChatMessageServiceImpl.java
[JD-281]Fix: 채팅 내역 상세 조회 api - Page에서 Slice로 변경
- Slice를 이용하여 프론트엔드에서 페이지와 크기를 받아와 페이지네이션을 처리한 뒤, 전후 페이지가 있는지 여부와 함께 메시지 리스트를 반환합니다.
[JD-281]: https://ttokttak.atlassian.net/browse/JD-281?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [JD-281]Fix: 채팅 내역 상세 조회 api - Page에서 Slice로 변경

- src/main/java/com/ttokttak/jellydiary/diary/controller/DiaryProfileController.java
- src/main/java/com/ttokttak/jellydiary/diary/entity/DiaryProfileEntity.java
- src/main/java/com/ttokttak/jellydiary/diary/service/DiaryProfileService.java
- src/main/java/com/ttokttak/jellydiary/diary/service/DiaryProfileServiceImpl.java
- src/main/java/com/ttokttak/jellydiary/exception/message/SuccessMsg.java
[JD-85]Feat: 다이어리 - 프로필 이미지 수정 api 구현
- 다이어리 프로필 이미지 수정 api 입니다. 먼저, 기존의 프로필 이미지를 삭제한 후 새로운 이미지를 업로드합니다. 이미지를 업로드하지 않은 경우에는 프로필 이미지가 null로 설정됩니다.
[JD-85]: https://ttokttak.atlassian.net/browse/JD-85?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [JD-85]Feat: 다이어리 - 프로필 이미지 수정 api 구현

- src/main/java/com/ttokttak/jellydiary/user/controller/ReissueController.java
- src/main/java/com/ttokttak/jellydiary/user/entity/RefreshTokenEntity.java
- src/main/java/com/ttokttak/jellydiary/user/handler/CustomSuccessHandler.java
- src/main/java/com/ttokttak/jellydiary/user/repository/RefreshTokenRepository.java
- src/main/java/com/ttokttak/jellydiary/user/service/RefreshTokenService.java
[JD-287]Fix: 로그인 성공 후 발급한 액세스토큰의 값이 Redirect된 헤더에 나오지 않는 문제 해결
- 로그인 성공 핸들러에서 리프레시 토큰을 발급한 후 중간페이지로 리다이렉트
- 리다이렉트된 곳에서 약속된 api로 프론트 측에서 액세스토큰 발급요청
=> 리다이렉트 토큰을 검증하는 로직도 추가하였습니다.
[JD-287]: https://ttokttak.atlassian.net/browse/JD-287?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [JD-287]Fix: 로그인 성공 후 발급한 액세스토큰의 값이 Redirect된 헤더에 나오지 않는 문제 해결

- src/main/java/com/ttokttak/jellydiary/comment/service/CommentServiceImpl.java
- src/main/java/com/ttokttak/jellydiary/diarypost/service/DiaryPostServiceImpl.java
- src/main/java/com/ttokttak/jellydiary/exception/message/SuccessMsg.java
- src/main/java/com/ttokttak/jellydiary/like/service/PostLikeServiceImpl.java
- src/main/java/com/ttokttak/jellydiary/notification/controller/NotificationController.java
- src/main/java/com/ttokttak/jellydiary/notification/dto/NotificationGetListResponseDto.java
- src/main/java/com/ttokttak/jellydiary/notification/entity/NotificationEntity.java
- src/main/java/com/ttokttak/jellydiary/notification/entity/NotificationSettingEntity.java
- src/main/java/com/ttokttak/jellydiary/notification/mapper/NotificationMapper.java
- src/main/java/com/ttokttak/jellydiary/notification/repository/NotificationRepository.java
- src/main/java/com/ttokttak/jellydiary/notification/repository/NotificationSettingRepository.java
- src/main/java/com/ttokttak/jellydiary/notification/service/NotificationService.java
- src/main/java/com/ttokttak/jellydiary/notification/service/NotificationServiceImpl.java
- src/main/java/com/ttokttak/jellydiary/user/dto/UserNotificationSettingRequestDto.java
- src/main/java/com/ttokttak/jellydiary/user/dto/UserNotificationSettingResponseDto.java
- src/main/java/com/ttokttak/jellydiary/user/entity/UserEntity.java
- src/main/java/com/ttokttak/jellydiary/user/service/UserServiceImpl.java
[JD-298]
- 알림 리스트 조회 api 를 추가하였습니다.
- notification setting에 따라 알림 발송 여부가 결정되기 때문에 해당 로직을 게시물 좋아요, 게시물 생성, 게시물 삭제, 댓글 생성, 답글 생성에 추가하였습니다.
- notification setting entity에 구독알림을 뜻하는 subscribe를 추가 후 관련 로직을 수정하였습니다.
[JD-298]: https://ttokttak.atlassian.net/browse/JD-298?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [JD-298]Feat: 알림리스트 조회 api 구현 및 notification setting entity에 구독 추가 후 관련 로직 수정

- src/main/java/com/ttokttak/jellydiary/user/service/CustomOAuth2UserService.java
- src/main/java/com/ttokttak/jellydiary/user/service/UserServiceImpl.java
[JD-299]
- notification setting entity에 구독 추가 후 수정하지 않은 CustomOAuth2UserService을 수정하였습니다.
[JD-299]: https://ttokttak.atlassian.net/browse/JD-299?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [JD-299]Fix: notification setting entity에 구독 추가 후 수정하지 않은 CustomOAuth2UserService 수정

- src/main/java/com/ttokttak/jellydiary/jwt/JWTFilter.java
- src/main/java/com/ttokttak/jellydiary/jwt/JWTUtil.java
[JD-305]Fix: JWTFilter, JWTUtil 수정
- /api/reissue 요청에 대해서 JWT 검증을 생략하도록 수정하고, 리프레시 토큰 유효기간 7일로 수정했습니다.
[JD-305]: https://ttokttak.atlassian.net/browse/JD-305?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [JD-305]Fix: JWTFilter, JWTUtil 수정

- src/main/java/com/ttokttak/jellydiary/config/SecurityConfig.java
[JD-309]
- 배포 환경에서 sse connect이 동작하지 않아 cors 문제로 의심되어 security에 백엔드 도메인을 추가하였습니다.
[JD-309]: https://ttokttak.atlassian.net/browse/JD-309?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [JD-309]Fix: 배포 환경에서 sse connect이 동작하지 않아 security에 백엔드 도메인 추가
